@font-face {
    font-family: 'Fira Sans';
    font-style: normal;
    font-weight: 400;
    font-display: swap;
    src: url('/sfsites/c/resource/DonationPageFonts/fira-sans-v18-latin_latin-ext-regular.woff2') format('woff2');
}

@font-face {
    font-family: 'Fira Sans';
    font-style: normal;
    font-weight: 500;
    font-display: swap;
    src: url('/sfsites/c/resource/DonationPageFonts/fira-sans-v18-latin_latin-ext-500.woff2') format('woff2');
}

@font-face {
    font-family: 'Fira Sans';
    font-style: normal;
    font-weight: 700;
    font-display: swap;
    src: url('/sfsites/c/resource/DonationPageFonts/fira-sans-v18-latin_latin-ext-700.woff2') format('woff2');
}

@font-face {
    font-family: 'Fira Sans';
    font-style: normal;
    font-weight: 800;
    font-display: swap;
    src: url('/sfsites/c/resource/DonationPageFonts/fira-sans-v18-latin_latin-ext-800.woff2') format('woff2');
}



@keyframes trsXscale {
    15% {
        transform: scale(1) translateZ(0)
    }

    20% {
        transform: scale(1.2) translate3d(4px,0,0)
    }

    25% {
        transform: scale(1.2) translateZ(0)
    }

    30% {
        transform: scale(1.2) translate3d(4px,0,0)
    }

    35% {
        transform: scale(1) translateZ(0)
    }
}

@-webkit-keyframes trsYscale {
    15% {
        transform: scale(1) translateZ(0)
    }

    20% {
        transform: scale(1.2) translate3d(0,4px,0)
    }

    25% {
        transform: scale(1.2) translateZ(0)
    }

    30% {
        transform: scale(1.2) translate3d(0,4px,0)
    }

    35% {
        transform: scale(1) translateZ(0)
    }
}

@keyframes trsYscale {
    15% {
        transform: scale(1) translateZ(0)
    }

    20% {
        transform: scale(1.2) translate3d(0,4px,0)
    }

    25% {
        transform: scale(1.2) translateZ(0)
    }

    30% {
        transform: scale(1.2) translate3d(0,4px,0)
    }

    35% {
        transform: scale(1) translateZ(0)
    }
}

@-webkit-keyframes trsX {
    15% {
        transform: translateZ(0)
    }

    20% {
        transform: translate3d(4px,0,0)
    }

    25% {
        transform: translateZ(0)
    }

    30% {
        transform: translate3d(4px,0,0)
    }

    35% {
        transform: translateZ(0)
    }
}

@keyframes trsX {
    15% {
        transform: translateZ(0)
    }

    20% {
        transform: translate3d(4px,0,0)
    }

    25% {
        transform: translateZ(0)
    }

    30% {
        transform: translate3d(4px,0,0)
    }

    35% {
        transform: translateZ(0)
    }
}

@-webkit-keyframes cartRotate {
    10% {
        transform: rotate(0)
    }

    15% {
        transform: rotate(-8deg)
    }

    20% {
        transform: rotate(0)
    }

    25% {
        transform: rotate(12deg)
    }

    30% {
        transform: rotate(0)
    }

    35% {
        transform: rotate(-9deg)
    }

    40% {
        transform: rotate(0)
    }

    45% {
        transform: rotate(6deg)
    }

    50% {
        transform: rotate(0)
    }
}

@keyframes cartRotate {
    10% {
        transform: rotate(0)
    }

    15% {
        transform: rotate(-8deg)
    }

    20% {
        transform: rotate(0)
    }

    25% {
        transform: rotate(12deg)
    }

    30% {
        transform: rotate(0)
    }

    35% {
        transform: rotate(-9deg)
    }

    40% {
        transform: rotate(0)
    }

    45% {
        transform: rotate(6deg)
    }

    50% {
        transform: rotate(0)
    }
}

@-webkit-keyframes rotating {
    0% {
        transform: rotate(0)
    }

    to {
        transform: rotate(1turn)
    }
}

@keyframes rotating {
    0% {
        transform: rotate(0)
    }

    to {
        transform: rotate(1turn)
    }
}

@-webkit-keyframes accordionBtnOpened {
    0% {
        transform: scale(1) translateZ(0) rotate(0)
    }

    15% {
        transform: scale(1) translateZ(0) rotate(0)
    }

    20% {
        transform: scale(1.2) translate3d(0,-4px,0) rotate(0)
    }

    25% {
        transform: scale(1.2) translateZ(0) rotate(0)
    }

    30% {
        transform: scale(1.2) translate3d(0,-4px,0) rotate(0)
    }

    35% {
        transform: scale(1) translateZ(0) rotate(0)
    }

    to {
        transform: scale(1) translateZ(0) rotate(0)
    }
}

@keyframes accordionBtnOpened {
    0% {
        transform: scale(1) translateZ(0) rotate(0)
    }

    15% {
        transform: scale(1) translateZ(0) rotate(0)
    }

    20% {
        transform: scale(1.2) translate3d(0,-4px,0) rotate(0)
    }

    25% {
        transform: scale(1.2) translateZ(0) rotate(0)
    }

    30% {
        transform: scale(1.2) translate3d(0,-4px,0) rotate(0)
    }

    35% {
        transform: scale(1) translateZ(0) rotate(0)
    }

    to {
        transform: scale(1) translateZ(0) rotate(0)
    }
}

@-webkit-keyframes accordionBtnClosed {
    0% {
        transform: scale(1) translateZ(0) rotate(180deg)
    }

    15% {
        transform: scale(1) translateZ(0) rotate(180deg)
    }

    20% {
        transform: scale(1.2) translate3d(0,4px,0) rotate(180deg)
    }

    25% {
        transform: scale(1.2) translateZ(0) rotate(180deg)
    }

    30% {
        transform: scale(1.2) translate3d(0,4px,0) rotate(180deg)
    }

    35% {
        transform: scale(1) translateZ(0) rotate(180deg)
    }

    to {
        transform: scale(1) translateZ(0) rotate(180deg)
    }
}

@keyframes accordionBtnClosed {
    0% {
        transform: scale(1) translateZ(0) rotate(180deg)
    }

    15% {
        transform: scale(1) translateZ(0) rotate(180deg)
    }

    20% {
        transform: scale(1.2) translate3d(0,4px,0) rotate(180deg)
    }

    25% {
        transform: scale(1.2) translateZ(0) rotate(180deg)
    }

    30% {
        transform: scale(1.2) translate3d(0,4px,0) rotate(180deg)
    }

    35% {
        transform: scale(1) translateZ(0) rotate(180deg)
    }

    to {
        transform: scale(1) translateZ(0) rotate(180deg)
    }
}

@-webkit-keyframes ripple {
    to {
        transform: scale(2.5);
        opacity: 0
    }
}

@keyframes ripple {
    to {
        transform: scale(2.5);
        opacity: 0
    }
}

html {
    font: 400 14px/1.714 Roboto,sans-serif;
    color: #362031;
    min-height: 100%;
    height: 100%;
    -webkit-text-size-adjust: 100%
}

@media only screen and (min-width: 1921px) {
    html {
        font-size:.77778vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    html {
        font-size:.77778vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    html {
        font-size:1.2381vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    html {
        font-size:1.51163vw
    }
}

@media only screen and (max-width: 640px) {
    html {
        font-size:3.73333vw
    }
}

* {
    text-rendering: optimizeLegibility;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    -webkit-tap-highlight-color: transparent
}

*,* :after,* :before {
    box-sizing: border-box
}

a,button,input,select,textarea {
    -webkit-appearance: none;
    border-radius: 0;
    font: inherit;
    outline: none
}

button {
    background: none;
    border: none;
    box-shadow: none;
    padding: 0;
    outline: none
}

a,button {
    cursor: pointer
}

a {
    text-decoration: none
}

b,h1,h2,h3,h4,h5,h6,strong {
    margin: 0;
    font-weight: 700;
    font-family: Roboto,sans-serif
}

picture {
    display: block;
    margin: 0
}

.btn {
    position: relative;
    padding: 21px 30px;
    border-radius: 4px;
    overflow: hidden
}

@media only screen and (min-width: 1921px) {
    .btn {
        padding:1.16667vw 1.66667vw;
        border-radius: .22222vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .btn {
        padding:1.16667vw 1.66667vw;
        border-radius: .22222vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .btn {
        padding:1.2381vw 2.85714vw;
        border-radius: .47619vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .btn {
        padding:1.51163vw 1.74419vw;
        border-radius: .5814vw
    }
}

@media only screen and (max-width: 640px) {
    .btn {
        padding:4.8vw 4vw;
        border-radius: 1.33333vw
    }
}

.btn__name {
    max-width: 100%;
    max-height: 100%;
    font-weight: 700;
    font-size: 20px;
    line-height: 1.4;
    color: #fff;
    word-break: break-word
}

@media only screen and (min-width: 1921px) {
    .btn__name {
        font-size:1.11111vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .btn__name {
        font-size:1.11111vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .btn__name {
        font-size:1.52381vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .btn__name {
        font-size:1.86047vw
    }
}

@media only screen and (max-width: 640px) {
    .btn__name {
        font-size:4.26667vw
    }
}

.btn--full {
    width: 100%
}

.btn--orange {
    background-color: #fa95c2;
    transition: background-color .3s cubic-bezier(.455,.03,.515,.955)
}

.btn--orange:hover {
    background-color: var(--redColorDim);
}

.btn--orange .button-ripple .ripple {
    background-color: hsla(0,0%,100%,.45)
}

.button-ripple {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    overflow: hidden
}

.button-ripple .ripple {
    border-radius: 50%;
    background-color: rgba(192,186,236,.6);
    position: absolute;
    transform: scale(0);
    -webkit-animation: ripple .5s cubic-bezier(.455,.03,.515,.955);
    animation: ripple .5s cubic-bezier(.455,.03,.515,.955);
    will-change: transform
}

.button-donate {
    position: fixed;
    right: 40px;
    bottom: 40px;
    z-index: 10;
    text-transform: uppercase;
    width: 320px;
    text-align: center;
    box-shadow: 0 20px 20px rgba(175,131,89,.25);
    transition-duration: .35s;
    transition-timing-function: cubic-bezier(.455,.03,.515,.955);
    transition-property: height,background-color,transform,opacity;
    opacity: 0;
    transform: translate3d(0,150%,0)
}

@media only screen and (min-width: 1921px) {
    .button-donate {
        right:2.22222vw;
        bottom: 2.22222vw;
        width: 17.77778vw;
        box-shadow: 0 1.11111vw 1.11111vw rgba(175,131,89,.25)
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .button-donate {
        right:2.22222vw;
        bottom: 2.22222vw;
        width: 17.77778vw;
        box-shadow: 0 1.11111vw 1.11111vw rgba(175,131,89,.25)
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .button-donate {
        right:2.38095vw;
        bottom: 2.38095vw;
        width: 23.80952vw;
        box-shadow: 0 1.42857vw 1.42857vw rgba(175,131,89,.25)
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .button-donate {
        right:2.90698vw;
        bottom: 2.90698vw;
        width: 29.06977vw;
        box-shadow: 0 1.74419vw 1.74419vw rgba(175,131,89,.25)
    }
}

@media only screen and (max-width: 640px) {
    .button-donate {
        right:4vw;
        bottom: 2.66667vw;
        left: 4vw;
        width: auto;
        padding: 3.46667vw 4vw;
        text-transform: inherit
    }
}

@media only screen and (max-width: 640px) {
    .button-donate .btn__name {
        font-size:6.4vw
    }
}

body.donate--hide .button-donate {
    opacity: 1;
    transform: translateZ(0)
}

.form {
    position: relative
}

.form__row {
    display: block;
    margin-top: 25px
}

@media only screen and (min-width: 1921px) {
    .form__row {
        margin-top:1.38889vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .form__row {
        margin-top:1.38889vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .form__row {
        margin-top:2.38095vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .form__row {
        margin-top:2.90698vw
    }
}

@media only screen and (max-width: 640px) {
    .form__row {
        margin-top:6.66667vw
    }
}

.form__row__wrapper {
    display: flex;
    align-items: flex-start;
    margin-top: 25px
}

@media only screen and (min-width: 1921px) {
    .form__row__wrapper {
        margin-top:1.38889vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .form__row__wrapper {
        margin-top:1.38889vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .form__row__wrapper {
        margin-top:2.38095vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .form__row__wrapper {
        margin-top:2.90698vw
    }
}

@media only screen and (max-width: 640px) {
    .form__row__wrapper {
        margin-top:6.66667vw
    }
}

.form__row--noMarginTop,.form__row:first-child,.form__row__wrapper .form__row {
    margin-top: 0
}

.form__row--half-wrap {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-right: -12px;
    margin-left: -12px
}

@media only screen and (min-width: 1921px) {
    .form__row--half-wrap {
        margin-right:-.66667vw;
        margin-left: -.66667vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .form__row--half-wrap {
        margin-right:-.66667vw;
        margin-left: -.66667vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .form__row--half-wrap {
        margin-right:-1.14286vw;
        margin-left: -1.14286vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .form__row--half-wrap {
        margin-right:-1.39535vw;
        margin-left: -1.39535vw
    }
}

@media only screen and (max-width: 640px) {
    .form__row--half-wrap {
        margin-right:-3.2vw;
        margin-left: -3.2vw
    }
}

.form__row--half-wrap .input--half {
    flex: 1 1 auto;
    margin-right: 12px;
    margin-left: 12px
}

@media only screen and (min-width: 1921px) {
    .form__row--half-wrap .input--half {
        margin-right:.66667vw;
        margin-left: .66667vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .form__row--half-wrap .input--half {
        margin-right:.66667vw;
        margin-left: .66667vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .form__row--half-wrap .input--half {
        margin-right:1.14286vw;
        margin-left: 1.14286vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .form__row--half-wrap .input--half {
        margin-right:1.39535vw;
        margin-left: 1.39535vw
    }
}

@media only screen and (max-width: 640px) {
    .form__row--half-wrap .input--half {
        margin-right:3.2vw;
        margin-left: 3.2vw
    }
}

.form__error-msg {
    padding: 14px 20px;
    background-color: #f9efef;
    font-size: 13px;
    line-height: 1.53;
    color: #ec3039
}

@media only screen and (min-width: 1921px) {
    .form__error-msg {
        padding:.77778vw 1.11111vw;
        font-size: .72222vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .form__error-msg {
        padding:.77778vw 1.11111vw;
        font-size: .72222vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .form__error-msg {
        padding:1.33333vw 1.90476vw;
        font-size: 1.2381vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .form__error-msg {
        padding:1.62791vw 2.32558vw;
        font-size: 1.51163vw
    }
}

@media only screen and (max-width: 640px) {
    .form__error-msg {
        padding:3.73333vw 5.33333vw;
        font-size: 3.46667vw
    }
}

.input:hover .input__field {
    border-color: #f3f0eb;
    box-shadow: 0 10px 20px rgba(43,55,51,.05)
}

@media only screen and (min-width: 1921px) {
    .input:hover .input__field {
        box-shadow:0 .55556vw 1.11111vw rgba(43,55,51,.05)
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .input:hover .input__field {
        box-shadow:0 .55556vw 1.11111vw rgba(43,55,51,.05)
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .input:hover .input__field {
        box-shadow:0 .95238vw 1.90476vw rgba(43,55,51,.05)
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .input:hover .input__field {
        box-shadow:0 1.16279vw 2.32558vw rgba(43,55,51,.05)
    }
}

@media only screen and (max-width: 640px) {
    .input:hover .input__field {
        box-shadow:0 2.66667vw 5.33333vw rgba(43,55,51,.05)
    }
}

.input.is-error .input__field {
    border-color: #ec3039!important
}

.input__label {
    display: block;
    margin-bottom: 10px;
    font-weight: 500
}

@media only screen and (min-width: 1921px) {
    .input__label {
        margin-bottom:.55556vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .input__label {
        margin-bottom:.55556vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .input__label {
        margin-bottom:.95238vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .input__label {
        margin-bottom:1.16279vw;
        font-size: 1.51163vw
    }
}

@media only screen and (max-width: 640px) {
    .input__label {
        margin-bottom:2.66667vw;
        font-size: 3.46667vw
    }
}

.input__wrapper {
    position: relative
}

.input__field {
    display: block;
    width: 100%;
    background-color: #fff;
    border: 1px solid transparent;
    border-radius: 4px;
    resize: none;
    outline: none;
    padding: 12px 22px;
    font-weight: 500;
    transition: border-color .35s ease,padding .35s ease
}

@media only screen and (min-width: 1921px) {
    .input__field {
        padding:.77778vw 1.11111vw;
        border-width: .05556vw;
        border-radius: .22222vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .input__field {
        padding:.77778vw 1.11111vw;
        border-width: .05556vw;
        border-radius: .22222vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .input__field {
        padding:.95238vw 1.42857vw;
        border-radius: .38095vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .input__field {
        padding:1.16279vw 1.74419vw;
        border-radius: .46512vw
    }
}

@media only screen and (max-width: 640px) {
    .input__field {
        padding:2.66667vw 4vw;
        border-width: .26667vw;
        border-radius: 1.06667vw
    }
}

.input__field:focus {
    border-color: #f3f0eb
}

.input__field[type=number]::-webkit-inner-spin-button,.input__field[type=number]::-webkit-outer-spin-button {
    -webkit-appearance: none;
    margin: 0
}

.custom-select {
    position: relative;
    outline: none;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    cursor: pointer
}

.custom-select select {
    position: absolute;
    top: 0;
    left: 0;
    display: block;
    width: 100%;
    height: 100%;
    pointer-events: none;
    opacity: 0
}

@media only screen and (max-width: 640px) {
    .custom-select select {
        pointer-events:all
    }
}

@media only screen and (max-width: 640px) {
    .custom-select select option[value=none] {
        display:none!important
    }
}

.custom-select__head {
    position: relative;
    display: block;
    width: 100%;
    background-color: #fff;
    border: 1px solid transparent;
    border-radius: 4px;
    resize: none;
    outline: none;
    padding: 12px 60px 12px 22px;
    font-weight: 500;
    text-transform: capitalize;
    transition: border-color .35s ease,padding .35s ease
}

@media only screen and (min-width: 1921px) {
    .custom-select__head {
        border-width:.05556vw;
        border-radius: .22222vw;
        padding: .66667vw 3.33333vw .66667vw 1.22222vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .custom-select__head {
        border-width:.05556vw;
        border-radius: .22222vw;
        padding: .66667vw 3.33333vw .66667vw 1.22222vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .custom-select__head {
        border-width:.09524vw;
        border-radius: .38095vw;
        padding: .95238vw 3.80952vw .95238vw 1.71429vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .custom-select__head {
        border-width:.11628vw;
        border-radius: .46512vw;
        padding: 1.16279vw 4.65116vw 1.16279vw 2.09302vw
    }
}

@media only screen and (max-width: 640px) {
    .custom-select__head {
        border-width:.26667vw;
        border-radius: 1.06667vw;
        padding: 3.2vw 10.66667vw 3.2vw 5.86667vw
    }
}

.custom-select__head .svg {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    display: block;
    margin: auto;
    fill: #362031;
    content: "";
    left: auto;
    right: 20px;
    transform: rotate(-180deg);
    transition: transform .35s cubic-bezier(.4,0,0,1)
}

@media only screen and (min-width: 1921px) {
    .custom-select__head .svg {
        right:1.11111vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .custom-select__head .svg {
        right:1.11111vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .custom-select__head .svg {
        right:1.14286vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .custom-select__head .svg {
        right:2.32558vw
    }
}

@media only screen and (max-width: 640px) {
    .custom-select__head .svg {
        right:5.33333vw
    }
}

.custom-select__head:hover {
    border-color: #f3f0eb;
    box-shadow: 0 10px 20px rgba(43,55,51,.05)
}

.custom-select__head:focus {
    border-color: #f3f0eb
}

.custom-select__input {
    position: absolute;
    top: 0;
    left: 0;
    display: block;
    width: 100%;
    height: 100%;
    padding: inherit;
    background: #fff;
    border: none;
    outline: none;
    color: #4f3549
}

.custom-select__input::-webkit-input-placeholder {
    color: #9b8f97
}

.custom-select__input:-moz-placeholder,.custom-select__input::-moz-placeholder {
    color: #9b8f97
}

.custom-select__input:-ms-input-placeholder {
    color: #9b8f97
}

.custom-select__input:focus::-webkit-input-placeholder {
    color: #9b8f97
}

.custom-select__input:focus:-moz-placeholder,.custom-select__input:focus::-moz-placeholder {
    color: #9b8f97
}

.custom-select__input:focus:-ms-input-placeholder {
    color: #9b8f97
}

.custom-select__content {
    position: absolute;
    overflow-x: hidden;
    overflow-y: auto;
    top: 100%;
    left: 0;
    z-index: 2;
    display: block;
    width: calc(100% + 2px);
    max-height: 216px;
    margin: 0 -1px;
    border: 1px solid #f3f0eb;
    background: #fff;
    opacity: 0;
    pointer-events: none;
    transition: opacity .3s;
    box-shadow: 0 get-vw(5px) get-vw(10px) rgba(97,168,162,.08)
}

@media only screen and (min-width: 1921px) {
    .custom-select__content {
        max-height:12vw;
        margin: 0 -.05556vw;
        border-width: .05556vw;
        box-shadow: 0 .55556vw 1.11111vw rgba(0,0,0,.05)
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .custom-select__content {
        max-height:12vw;
        margin: 0 -.05556vw;
        border-width: .05556vw;
        box-shadow: 0 .55556vw 1.11111vw rgba(0,0,0,.05)
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .custom-select__content {
        max-height:20.57143vw;
        border-width: .09524vw;
        box-shadow: 0 .95238vw 1.90476vw rgba(0,0,0,.05)
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .custom-select__content {
        max-height:25.11628vw;
        border-width: .11628vw;
        box-shadow: 0 1.16279vw 2.32558vw rgba(0,0,0,.05)
    }
}

@media only screen and (max-width: 640px) {
    .custom-select__content {
        max-height:57.6vw;
        margin: 0 -.26667vw;
        box-shadow: 0 2.66667vw 5.33333vw rgba(0,0,0,.05)
    }
}

.custom-select__content::-webkit-scrollbar {
    width: 3px;
    height: 3px;
    background-color: #f3f0eb
}

@media only screen and (min-width: 1921px) {
    .custom-select__content::-webkit-scrollbar {
        width:.16667vw;
        height: .16667vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .custom-select__content::-webkit-scrollbar {
        width:.16667vw;
        height: .16667vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .custom-select__content::-webkit-scrollbar {
        width:.28571vw;
        height: .28571vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .custom-select__content::-webkit-scrollbar {
        width:.34884vw;
        height: .34884vw
    }
}

@media only screen and (max-width: 640px) {
    .custom-select__content::-webkit-scrollbar {
        width:.8vw;
        height: .8vw
    }
}

.custom-select__content::-webkit-scrollbar-thumb {
    background-color: #fa95c2
}

.custom-select__list {
    background: #fff
}

.custom-select__item {
    overflow: hidden;
    padding: 10px 22px;
    background: #fff;
    font-weight: 500;
    color: #6b5a65;
    white-space: nowrap;
    text-overflow: ellipsis;
    transition: background .3s;
    text-transform: capitalize
}

@media only screen and (min-width: 1921px) {
    .custom-select__item {
        padding:.55556vw 1.66667vw;
        font-size: .77778vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .custom-select__item {
        padding:.55556vw 1.66667vw;
        font-size: .77778vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .custom-select__item {
        padding:.95238vw 1.71429vw;
        font-size: 1.33333vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .custom-select__item {
        padding:1.16279vw 2.09302vw;
        font-size: 1.62791vw
    }
}

@media only screen and (max-width: 640px) {
    .custom-select__item {
        padding:2.66667vw 8vw;
        font-size: 3.73333vw
    }
}

.custom-select__item:hover {
    background: #f3f0eb
}

.custom-select__item.is-active {
    background: #f3f0eb;
    color: #362031
}

.custom-select__item.is-hidden,.custom-select__item.is-none {
    display: none
}

.custom-select.is-opened .custom-select__head .svg {
    transform: rotate(0)
}

.custom-select.is-opened .custom-select__content {
    opacity: 1;
    pointer-events: all
}

.radio-group {
    display: flex;
    flex-direction: column;
    margin: 40px 0 30px
}

@media only screen and (min-width: 1921px) {
    .radio-group {
        margin:2.22222vw 0 1.66667vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .radio-group {
        margin:2.22222vw 0 1.66667vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .radio-group {
        margin:3.80952vw 0 2.85714vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .radio-group {
        margin:4.65116vw 0 3.48837vw
    }
}

@media only screen and (max-width: 640px) {
    .radio-group {
        margin:10.66667vw 0 8vw
    }
}

.radio-group .radio:first-child {
    margin-top: 0
}

.radio-group .radio:last-child {
    margin-bottom: 0
}

.radio {
    position: relative;
    display: inline-flex;
    flex-direction: column;
    cursor: pointer;
    margin: 10px 0;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    outline: none
}

@media only screen and (min-width: 1921px) {
    .radio {
        margin:.55556vw 0
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .radio {
        margin:.55556vw 0
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .radio {
        margin:.95238vw 0
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .radio {
        margin:1.16279vw 0
    }
}

@media only screen and (max-width: 640px) {
    .radio {
        margin:2.66667vw 0
    }
}

.radio.is-error .radio__text:before {
    border-color: #ec3039!important
}

.radio__input {
    position: absolute;
    opacity: 0;
    pointer-events: none
}

.radio__input:checked~.radio__text {
    color: #362031
}

.radio__input:checked~.radio__text:after {
    transform: scale(1)
}

.radio__input:checked~.radio__content {
    display: block
}

.radio__text {
    position: relative;
    padding-left: 52px;
    font-weight: 500;
    font-size: 18px;
    line-height: 1.66;
    color: #9b8f97;
    transition: color .35s cubic-bezier(.4,0,0,1)
}

@media only screen and (min-width: 1921px) {
    .radio__text {
        padding-left:2.88889vw;
        font-size: 1vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .radio__text {
        padding-left:2.88889vw;
        font-size: 1vw
    }
}

@media only screen and (max-width: 1050px) {
    .radio__text {
        line-height:1.714
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .radio__text {
        padding-left:3.80952vw;
        font-size: 1.33333vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .radio__text {
        padding-left:4.65116vw;
        font-size: 1.62791vw
    }
}

@media only screen and (max-width: 640px) {
    .radio__text {
        padding-left:10.66667vw;
        font-size: 3.73333vw
    }
}

.radio__text:before {
    content: "";
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    display: block;
    width: 26px;
    height: 26px;
    margin: 0 auto;
    border: 1px solid #9b8f97;
    border-radius: 50%;
    transition: border-color .35s ease
}

@media only screen and (min-width: 1921px) {
    .radio__text:before {
        width:1.44444vw;
        height: 1.44444vw;
        border-width: .05556vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .radio__text:before {
        width:1.44444vw;
        height: 1.44444vw;
        border-width: .05556vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .radio__text:before {
        width:2.28571vw;
        height: 2.28571vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .radio__text:before {
        width:2.7907vw;
        height: 2.7907vw
    }
}

@media only screen and (max-width: 640px) {
    .radio__text:before {
        width:6.4vw;
        height: 6.4vw;
        border-width: .26667vw
    }
}

.radio__text:after {
    content: "";
    position: absolute;
    top: 8px;
    left: 8px;
    transform: scale(0);
    width: 10px;
    height: 10px;
    background: #362031;
    border-radius: 50%;
    transition: transform .35s cubic-bezier(.4,0,0,1);
    will-change: transform
}

@media only screen and (min-width: 1921px) {
    .radio__text:after {
        top:.44444vw;
        left: .44444vw;
        width: .55556vw;
        height: .55556vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .radio__text:after {
        top:.44444vw;
        left: .44444vw;
        width: .55556vw;
        height: .55556vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .radio__text:after {
        top:.66667vw;
        left: .66667vw;
        width: .95238vw;
        height: .95238vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .radio__text:after {
        top:.81395vw;
        left: .81395vw;
        width: 1.16279vw;
        height: 1.16279vw
    }
}

@media only screen and (max-width: 640px) {
    .radio__text:after {
        top:1.86667vw;
        left: 1.86667vw;
        width: 2.66667vw;
        height: 2.66667vw
    }
}

.radio__text a {
    text-decoration: underline;
    font: inherit;
    color: inherit
}

.radio__text a:focus,.radio__text a:hover {
    text-decoration: none
}

.radio__content {
    display: none;
    margin-bottom: 20px;
    padding-top: 35px
}

@media only screen and (min-width: 1921px) {
    .radio__content {
        margin-bottom:1.11111vw;
        padding-top: 1.94444vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .radio__content {
        margin-bottom:1.11111vw;
        padding-top: 1.94444vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .radio__content {
        margin-bottom:1.90476vw;
        padding-top: 2.85714vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .radio__content {
        margin-bottom:2.32558vw;
        padding-top: 4.06977vw
    }
}

@media only screen and (max-width: 640px) {
    .radio__content {
        margin-bottom:5.33333vw;
        padding-top: 9.33333vw
    }
}

.radio__content img {
    display: block;
    max-width: 100%
}

.radio:focus .radio__text:before,.radio:hover .radio__text:before {
    border-color: #9b8f97
}

.radio-rect-group {
    display: flex;
    margin: 30px -5px 15px
}

@media only screen and (min-width: 1921px) {
    .radio-rect-group {
        margin:1.66667vw -.27778vw .83333vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .radio-rect-group {
        margin:1.66667vw -.27778vw .83333vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .radio-rect-group {
        margin:2.38095vw -.47619vw 1.42857vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .radio-rect-group {
        margin:2.90698vw -.5814vw 1.74419vw
    }
}

@media only screen and (max-width: 640px) {
    .radio-rect-group {
        margin:4vw -1.33333vw
    }
}

.radio-rect-group .radio-rect {
    flex: 1 0 12.5%;
    margin: 0 5px
}

@media only screen and (min-width: 1921px) {
    .radio-rect-group .radio-rect {
        margin:0 .27778vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .radio-rect-group .radio-rect {
        margin:0 .27778vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .radio-rect-group .radio-rect {
        margin:0 .47619vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .radio-rect-group .radio-rect {
        margin:0 .5814vw
    }
}

@media only screen and (max-width: 640px) {
    .radio-rect-group .radio-rect {
        margin:0 1.33333vw
    }
}

.radio-rect-group--md .radio-rect {
    height: 80px
}

@media only screen and (min-width: 1921px) {
    .radio-rect-group--md .radio-rect {
        height:4.44444vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .radio-rect-group--md .radio-rect {
        height:4.44444vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .radio-rect-group--md .radio-rect {
        height:5.71429vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .radio-rect-group--md .radio-rect {
        height:6.97674vw
    }
}

@media only screen and (max-width: 640px) {
    .radio-rect-group--md .radio-rect {
        height:16vw
    }
}

.radio-rect-group--md .radio-rect__text--small {
    font-size: 18px
}

@media only screen and (min-width: 1921px) {
    .radio-rect-group--md .radio-rect__text--small {
        font-size:1vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .radio-rect-group--md .radio-rect__text--small {
        font-size:1vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .radio-rect-group--md .radio-rect__text--small {
        font-size:1.33333vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .radio-rect-group--md .radio-rect__text--small {
        font-size:1.62791vw
    }
}

@media only screen and (max-width: 640px) {
    .radio-rect-group--md .radio-rect__text--small {
        font-size:3.73333vw
    }
}

.radio-rect-group--sm .radio-rect {
    height: 60px
}

@media only screen and (min-width: 1921px) {
    .radio-rect-group--sm .radio-rect {
        height:3.33333vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .radio-rect-group--sm .radio-rect {
        height:3.33333vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .radio-rect-group--sm .radio-rect {
        height:4.7619vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .radio-rect-group--sm .radio-rect {
        height:5.81395vw
    }
}

@media only screen and (max-width: 640px) {
    .radio-rect-group--sm .radio-rect {
        height:13.33333vw
    }
}

.radio-rect-group--sm .radio-rect__text {
    font-size: 16px
}

@media only screen and (min-width: 1921px) {
    .radio-rect-group--sm .radio-rect__text {
        font-size:.88889vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .radio-rect-group--sm .radio-rect__text {
        font-size:.88889vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .radio-rect-group--sm .radio-rect__text {
        font-size:1.33333vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .radio-rect-group--sm .radio-rect__text {
        font-size:1.62791vw
    }
}

@media only screen and (max-width: 640px) {
    .radio-rect-group--sm .radio-rect__text {
        font-size:3.73333vw
    }
}

.radio-rect {
    position: relative;
    display: inline-flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    border-radius: 4px;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    outline: none;
    background-color: #fff
}

@media only screen and (min-width: 1921px) {
    .radio-rect {
        border-radius:.22222vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .radio-rect {
        border-radius:.22222vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .radio-rect {
        border-radius:.38095vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .radio-rect {
        border-radius:.46512vw
    }
}

@media only screen and (max-width: 640px) {
    .radio-rect {
        border-radius:1.06667vw
    }
}

.radio-rect:hover .radio-rect__text {
    color: #362031
}

.radio-rect__text {
    pointer-events: none;
    font-weight: 700;
    font-size: 30px;
    line-height: 1.2;
    color: #9b8f97;
    transition: color .35s cubic-bezier(.455,.03,.515,.955)
}

@media only screen and (min-width: 1921px) {
    .radio-rect__text {
        font-size:1.66667vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .radio-rect__text {
        font-size:1.66667vw
    }
}

@media only screen and (max-width: 1050px) {
    .radio-rect__text {
        line-height:1.25
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .radio-rect__text {
        font-size:2.28571vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .radio-rect__text {
        font-size:2.7907vw
    }
}

@media only screen and (max-width: 640px) {
    .radio-rect__text {
        font-size:5.33333vw
    }
}

.radio-rect__text:after {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    display: block;
    width: 100%;
    height: 100%;
    border: 1px solid transparent;
    border-radius: .22222vw;
    transition: border .35s cubic-bezier(.455,.03,.515,.955)
}

@media only screen and (min-width: 1921px) {
    .radio-rect__text:after {
        border-width:.05556vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .radio-rect__text:after {
        border-width:.05556vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .radio-rect__text:after {
        border-radius:.38095vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .radio-rect__text:after {
        border-radius:.46512vw
    }
}

@media only screen and (max-width: 640px) {
    .radio-rect__text:after {
        border-width:.26667vw;
        border-radius: 1.06667vw
    }
}

.radio-rect__text:before {
    content: "";
    position: absolute;
    top: -9px;
    right: 5px;
    z-index: 1;
    display: block;
    width: 18px;
    height: 18px;
    border-radius: 50%;
    background-repeat: no-repeat;
    background-color: #362031;
    background-position: 50%;
    background-image: url(images/icons/icon-check.svg);
    background-size: 7px;
    opacity: 0;
    transform: scale(.4);
    transition: transform .35s cubic-bezier(.455,.03,.515,.955),opacity .35s cubic-bezier(.455,.03,.515,.955)
}

@media only screen and (min-width: 1921px) {
    .radio-rect__text:before {
        top:-.5vw;
        right: .27778vw;
        width: 1vw;
        height: 1vw;
        background-size: .38889vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .radio-rect__text:before {
        top:-.5vw;
        right: .27778vw;
        width: 1vw;
        height: 1vw;
        background-size: .38889vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .radio-rect__text:before {
        top:-.85714vw;
        right: .47619vw;
        width: 1.71429vw;
        height: 1.71429vw;
        background-size: .66667vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .radio-rect__text:before {
        top:-1.04651vw;
        right: .5814vw;
        width: 2.09302vw;
        height: 2.09302vw;
        background-size: .81395vw
    }
}

@media only screen and (max-width: 640px) {
    .radio-rect__text:before {
        top:-2.4vw;
        right: 1.33333vw;
        width: 4.8vw;
        height: 4.8vw;
        background-size: 1.86667vw
    }
}

.radio-rect__input {
    position: absolute;
    opacity: 0;
    pointer-events: none
}

.radio-rect__input:checked~.radio-rect__text {
    color: #362031
}

.radio-rect__input:checked~.radio-rect__text:after {
    border-color: #362031;
    box-shadow: 0 get-vw(5px) get-vw(10px) rgba(97,168,162,.08)
}

.radio-rect__input:checked~.radio-rect__text:before {
    opacity: 1;
    transform: scale(1)
}

.checkbox {
    position: relative;
    display: inline-flex;
    cursor: pointer;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    outline: none
}

.checkbox__input {
    position: absolute;
    opacity: 0;
    pointer-events: none
}

.checkbox__input:checked~.checkbox__text:after {
    transform: scale(1);
    background-color: #362031
}

.checkbox.is-error .checkbox__input:checked~.checkbox__text:before,.checkbox.is-error .checkbox__text:before {
    border-color: #ec3039
}

.checkbox__text {
    position: relative;
    padding-left: 44px;
    color: #6b5a65
}

@media only screen and (min-width: 1921px) {
    .checkbox__text {
        padding-left:2.44444vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .checkbox__text {
        padding-left:2.44444vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .checkbox__text {
        padding-left:3.80952vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .checkbox__text {
        padding-left:4.65116vw
    }
}

@media only screen and (max-width: 640px) {
    .checkbox__text {
        padding-left:10.66667vw;
        font-size: 3.46667vw
    }
}

.checkbox__text:after,.checkbox__text:before {
    content: "";
    position: absolute;
    top: 0;
    bottom: 0;
    display: block;
    margin: 0 auto
}

.checkbox__text:before {
    top: 2px;
    left: 3px;
    width: 18px;
    height: 18px;
    border: 1px solid #9b8f97;
    border-radius: 1px;
    transition: border-color .35s cubic-bezier(.455,.03,.515,.955)
}

@media only screen and (min-width: 1921px) {
    .checkbox__text:before {
        top:.11111vw;
        left: .16667vw;
        width: 1vw;
        height: 1vw;
        border-width: .05556vw;
        border-radius: .05556vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .checkbox__text:before {
        top:.11111vw;
        left: .16667vw;
        width: 1vw;
        height: 1vw;
        border-width: .05556vw;
        border-radius: .05556vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .checkbox__text:before {
        top:.19048vw;
        left: .28571vw;
        width: 1.71429vw;
        height: 1.71429vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .checkbox__text:before {
        top:.23256vw;
        left: .34884vw;
        width: 2.09302vw;
        height: 2.09302vw
    }
}

@media only screen and (max-width: 640px) {
    .checkbox__text:before {
        top:.53333vw;
        left: .8vw;
        width: 4.8vw;
        height: 4.8vw
    }
}

.checkbox__text:after {
    top: 2px;
    left: 3px;
    width: 18px;
    height: 18px;
    border-radius: 1px;
    background-image: url(images/icons/icon-check.svg);
    background-repeat: no-repeat;
    background-position: 50%;
    background-size: 10px;
    transform: scale(0);
    transition: transform .35s cubic-bezier(.4,0,0,1);
    will-change: transform
}

@media only screen and (min-width: 1921px) {
    .checkbox__text:after {
        top:.11111vw;
        left: .16667vw;
        width: 1vw;
        height: 1vw;
        background-size: .55556vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .checkbox__text:after {
        top:.11111vw;
        left: .16667vw;
        width: 1vw;
        height: 1vw;
        background-size: .55556vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .checkbox__text:after {
        top:.19048vw;
        left: .28571vw;
        width: 1.71429vw;
        height: 1.71429vw;
        background-size: .95238vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .checkbox__text:after {
        top:.23256vw;
        left: .34884vw;
        width: 2.09302vw;
        height: 2.09302vw;
        background-size: 1.16279vw
    }
}

@media only screen and (max-width: 640px) {
    .checkbox__text:after {
        top:.53333vw;
        left: .8vw;
        width: 4.8vw;
        height: 4.8vw;
        background-size: 2.66667vw
    }
}

.checkbox__text a {
    text-decoration: none;
    font: inherit
}

.checkbox__text a:focus,.checkbox__text a:hover {
    text-decoration: underline
}

.checkbox:hover .checkbox__text:before {
    border-color: #362031
}

#loader {
    transition: opacity .3s ease
}

.container {
    padding-right: 100px;
    padding-left: 100px
}

@media only screen and (min-width: 1921px) {
    .container {
        padding-right:5.55556vw;
        padding-left: 5.55556vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .container {
        padding-right:5.55556vw;
        padding-left: 5.55556vw
    }
}

@media only screen and (max-width: 1440px) and (min-width:1371px) {
    .container {
        padding-right:5.55556vw;
        padding-left: 5.55556vw
    }
}

@media only screen and (max-width: 1370px) and (min-width:1051px) {
    .container {
        padding-right:4.37956vw;
        padding-left: 4.37956vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .container {
        padding-right:3.80952vw;
        padding-left: 3.80952vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .container {
        padding-right:3.48837vw;
        padding-left: 3.48837vw
    }
}

@media only screen and (max-width: 640px) {
    .container {
        padding-right:5.33333vw;
        padding-left: 5.33333vw
    }
}

.h1,h1 {
    font: 700 60px/1 Roboto,sans-serif;
    letter-spacing: .033em
}

@media only screen and (min-width: 1921px) {
    .h1,h1 {
        font-size:3.33333vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .h1,h1 {
        font-size:3.33333vw
    }
}

@media only screen and (max-width: 1050px) {
    .h1,h1 {
        line-height:1.16
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .h1,h1 {
        font-size:3.42857vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .h1,h1 {
        font-size:4.18605vw
    }
}

@media only screen and (max-width: 640px) {
    .h1,h1 {
        font-size:9.6vw
    }
}

.h2,h2 {
    font: 700 48px/1.25 Roboto,sans-serif
}

@media only screen and (min-width: 1921px) {
    .h2,h2 {
        font-size:2.66667vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .h2,h2 {
        font-size:2.66667vw
    }
}

@media only screen and (max-width: 1050px) {
    .h2,h2 {
        line-height:1.2
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .h2,h2 {
        font-size:2.85714vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .h2,h2 {
        font-size:3.48837vw
    }
}

@media only screen and (max-width: 640px) {
    .h2,h2 {
        font-size:8vw
    }
}

.h3,h3 {
    font: 700 36px/1.33 Roboto,sans-serif
}

@media only screen and (min-width: 1921px) {
    .h3,h3 {
        font-size:2vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .h3,h3 {
        font-size:2vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .h3,h3 {
        font-size:2.28571vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .h3,h3 {
        font-size:2.7907vw
    }
}

@media only screen and (max-width: 640px) {
    .h3,h3 {
        font-size:6.4vw
    }
}

[data-visibility] {
    transition: opacity .3s linear .1s
}

[data-visibility]:not(.is-visible) {
    opacity: 0
}

.svg {
    pointer-events: none;
    display: inline-flex;
    width: 24px;
    height: 24px
}

@media only screen and (min-width: 1921px) {
    .svg {
        width:1.33333vw;
        height: 1.33333vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .svg {
        width:1.33333vw;
        height: 1.33333vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .svg {
        width:2.28571vw;
        height: 2.28571vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .svg {
        width:2.7907vw;
        height: 2.7907vw
    }
}

@media only screen and (max-width: 640px) {
    .svg {
        width:6.4vw;
        height: 6.4vw
    }
}

.fill--black {
    fill: #4f3549;
    color: #4f3549
}

.fill--dark {
    fill: #362031;
    color: #362031
}

.fill--white {
    fill: #fff;
    color: #fff
}

.fill--blue {
    fill: #362031;
    color: #362031
}

.donate {
    width: 100%;
    padding: 60px 50px;
    border-radius: 8px;
    background: #f3f0eb;
    transition-timing-function: cubic-bezier(.455,.03,.515,.955);
    transition-duration: .35s;
    transition-property: transform,border-radius
}

@media only screen and (min-width: 1921px) {
    .donate {
        padding:3.33333vw 2.77778vw;
        border-radius: .44444vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .donate {
        padding:3.33333vw 2.77778vw;
        border-radius: .44444vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .donate {
        padding:3.80952vw 2.85714vw;
        border-radius: .7619vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate {
        padding:4.65116vw 2.32558vw;
        border-top-left-radius: 0;
        border-top-right-radius: 0
    }
}

@media only screen and (max-width: 640px) {
    .donate {
        padding:10.66667vw 5.33333vw;
        border-top-right-radius: 0;
        border-top-left-radius: 0
    }
}

@media only screen and (max-width: 860px) {
    [data-toggle-wrap].is-open .donate {
        opacity:0;
        display: none;
        visibility: hidden
    }
}

.donate__wrapper {
    position: -webkit-sticky;
    position: sticky;
    top: 0;
    z-index: 10;
    width: 550px;
    margin-right: 120px;
    margin-bottom: 50px;
    margin-left: auto
}

@media only screen and (min-width: 1921px) {
    .donate__wrapper {
        width:30.55556vw;
        margin-right: 6.66667vw;
        margin-bottom: 2.77778vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .donate__wrapper {
        width:30.55556vw;
        margin-right: 6.66667vw;
        margin-bottom: 2.77778vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .donate__wrapper {
        width:38.09524vw;
        margin-right: 5.71429vw;
        margin-bottom: 3.80952vw
    }
}

@media only screen and (max-width: 860px) {
    .donate__wrapper {
        position:relative!important;
        top: auto!important;
        order: 1
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate__wrapper {
        width:calc(100% - 34.88372vw);
        margin: -9.30233vw 17.44186vw 1.74419vw
    }
}

@media only screen and (max-width: 640px) {
    .donate__wrapper {
        position:relative;
        top: auto;
        width: calc(100% - 8vw);
        margin-top: -21.33333vw;
        margin-right: 4vw;
        margin-bottom: 4vw
    }
}

.donate__button {
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    cursor: pointer;
    position: relative;
    z-index: 1;
    padding: 15px;
    background-color: #362031;
    border-radius: 8px;
    overflow: hidden
}

@media only screen and (min-width: 1921px) {
    .donate__button {
        padding:.83333vw;
        border-radius: .44444vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .donate__button {
        padding:.83333vw;
        border-radius: .44444vw
    }
}

@media only screen and (min-width: 1051px) {
    .donate__button {
        display:none
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .donate__button {
        display:none
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate__button {
        padding:1.74419vw;
        border-radius: .93023vw
    }
}

@media only screen and (max-width: 640px) {
    .donate__button {
        padding:4vw;
        border-radius: 2.13333vw
    }
}

[data-toggle-wrap]:not(.is-open) .donate__button {
    border-bottom-left-radius: 0;
    border-bottom-right-radius: 0
}

.donate__button__name {
    pointer-events: none;
    font-weight: 700;
    font-size: 24px;
    line-height: 1.25;
    color: #fff;
    text-align: center
}

@media only screen and (min-width: 1921px) {
    .donate__button__name {
        font-size:1.33333vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .donate__button__name {
        font-size:1.33333vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .donate__button__name {
        font-size:2.28571vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate__button__name {
        font-size:2.7907vw
    }
}

@media only screen and (max-width: 640px) {
    .donate__button__name {
        font-size:6.4vw
    }
}

.donate__button__icon {
    pointer-events: none;
    position: absolute;
    top: 50%;
    right: 20px;
    transform: translateY(-50%);
    z-index: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    width: 32px;
    height: 32px;
    transition: transform .35s cubic-bezier(.4,0,0,1)
}

@media only screen and (min-width: 1921px) {
    .donate__button__icon {
        right:1.11111vw;
        width: 1.77778vw;
        height: 1.77778vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .donate__button__icon {
        right:1.11111vw;
        width: 1.77778vw;
        height: 1.77778vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .donate__button__icon {
        right:1.90476vw;
        width: 3.04762vw;
        height: 3.04762vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate__button__icon {
        right:2.32558vw;
        width: 3.72093vw;
        height: 3.72093vw
    }
}

@media only screen and (max-width: 640px) {
    .donate__button__icon {
        right:5.33333vw;
        width: 8.53333vw;
        height: 8.53333vw
    }
}

.donate__button__icon .svg {
    width: 100%;
    height: 100%
}

@media only screen and (max-width: 860px) {
    [data-toggle-wrap].is-open .donate__button__icon {
        transform:translateY(-50%) rotate(-180deg)
    }
}

.donate__button .button-ripple .ripple {
    background-color: hsla(0,0%,100%,.45)
}

.donate__title {
    max-width: 100%;
    margin-bottom: 20px;
    line-height: 1.16;
    text-align: center;
    word-break: break-word
}

@media only screen and (min-width: 1921px) {
    .donate__title {
        margin-bottom:1.11111vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .donate__title {
        margin-bottom:1.11111vw
    }
}

@media only screen and (max-width: 1050px) {
    .donate__title {
        line-height:1.25;
        margin-bottom: 1.90476vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate__title {
        margin-bottom:2.32558vw
    }
}

@media only screen and (max-width: 640px) {
    .donate__title {
        margin-bottom:5.33333vw
    }
}

.donate__title--tab:not(.is-active) {
    display: none
}

.donate__subtitle {
    margin-bottom: 30px;
    text-align: center
}

@media only screen and (min-width: 1921px) {
    .donate__subtitle {
        margin-bottom:1.66667vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .donate__subtitle {
        margin-bottom:1.66667vw
    }
}

@media only screen and (max-width: 1050px) {
    .donate__subtitle {
        margin-bottom:2.38095vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate__subtitle {
        margin-bottom:2.90698vw
    }
}

@media only screen and (max-width: 640px) {
    .donate__subtitle {
        margin-bottom:6.66667vw
    }
}

.donate__select-group {
    margin-bottom: 40px
}

@media only screen and (min-width: 1921px) {
    .donate__select-group {
        margin-bottom:2.22222vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .donate__select-group {
        margin-bottom:2.22222vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .donate__select-group {
        margin-bottom:2.85714vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate__select-group {
        margin-bottom:3.48837vw
    }
}

@media only screen and (max-width: 640px) {
    .donate__select-group {
        margin-bottom:8vw
    }
}

.donate__select-group .donate__ttl {
    margin-bottom: 20px;
    font-weight: 700;
    font-size: 16px;
    line-height: 1.5;
    text-align: center
}

@media only screen and (min-width: 1921px) {
    .donate__select-group .donate__ttl {
        margin-bottom:1.11111vw;
        font-size: .88889vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .donate__select-group .donate__ttl {
        margin-bottom:1.11111vw;
        font-size: .88889vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .donate__select-group .donate__ttl {
        margin-bottom:1.42857vw;
        font-size: 1.42857vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate__select-group .donate__ttl {
        margin-bottom:1.74419vw;
        font-size: 1.74419vw
    }
}

@media only screen and (max-width: 640px) {
    .donate__select-group .donate__ttl {
        margin-bottom:4vw;
        font-size: 4vw
    }
}

.donate__btn {
    display: flex;
    align-items: center;
    justify-content: center;
    margin-top: 35px
}

@media only screen and (min-width: 1921px) {
    .donate__btn {
        margin-top:1.94444vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .donate__btn {
        margin-top:1.94444vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .donate__btn {
        margin-top:3.33333vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate__btn {
        margin-top:4.06977vw
    }
}

@media only screen and (max-width: 640px) {
    .donate__btn {
        margin-top:9.33333vw
    }
}

.donate .secure-info {
    display: flex;
    align-items: center;
    justify-content: center;
    margin-top: 40px
}

@media only screen and (min-width: 1921px) {
    .donate .secure-info {
        margin-top:2.22222vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .donate .secure-info {
        margin-top:2.22222vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .donate .secure-info {
        margin-top:2.85714vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate .secure-info {
        margin-top:4.65116vw
    }
}

@media only screen and (max-width: 640px) {
    .donate .secure-info {
        margin-top:10.66667vw
    }
}

.donate .secure-info__name {
    color: #6b5a65
}

.donate .secure-info svg {
    width: 32px;
    height: 32px;
    margin-right: 10px
}

@media only screen and (min-width: 1921px) {
    .donate .secure-info svg {
        width:1.77778vw;
        height: 1.77778vw;
        margin-right: .55556vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .donate .secure-info svg {
        width:1.77778vw;
        height: 1.77778vw;
        margin-right: .55556vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .donate .secure-info svg {
        width:2.66667vw;
        height: 2.66667vw;
        margin-right: .95238vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate .secure-info svg {
        width:3.25581vw;
        height: 3.25581vw;
        margin-right: 1.16279vw
    }
}

@media only screen and (max-width: 640px) {
    .donate .secure-info svg {
        width:7.46667vw;
        height: 7.46667vw;
        margin-right: 2.66667vw
    }
}

.donate .custom-select__input {
    text-transform: capitalize
}

.donate .custom-select__input::-webkit-input-placeholder {
    color: #362031
}

.donate .custom-select__input:-moz-placeholder,.donate .custom-select__input::-moz-placeholder {
    color: #362031
}

.donate .custom-select__input:-ms-input-placeholder {
    color: #362031
}

.donate__custom {
    position: relative;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    max-width: 100%
}

.donate__custom-amount {
    max-width: 52.5%;
    width: 100%;
    margin-right: auto
}

@media only screen and (max-width: 860px) {
    .donate__custom-amount {
        max-width:50%
    }
}

.donate__custom-amount__input {
    display: flex;
    align-items: center;
    max-width: 100%;
    width: 100%;
    min-height: 50px
}

@media only screen and (min-width: 1921px) {
    .donate__custom-amount__input {
        min-height:2.77778vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .donate__custom-amount__input {
        min-height:2.77778vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .donate__custom-amount__input {
        min-height:4.7619vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate__custom-amount__input {
        min-height:5.81395vw
    }
}

@media only screen and (max-width: 640px) {
    .donate__custom-amount__input {
        min-height:13.33333vw
    }
}

.donate__custom-amount__input input {
    display: block;
    max-width: 100%;
    width: 100%;
    background: none;
    outline: none;
    border: none;
    padding: 0;
    font-weight: 800;
    line-height: 1;
    font-size: 100px;
    color: #362031;
    text-align: right
}

@media only screen and (min-width: 1921px) {
    .donate__custom-amount__input input {
        font-size:5.55556vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .donate__custom-amount__input input {
        font-size:5.55556vw
    }
}

@media only screen and (max-width: 1440px) and (min-width:1371px) {
    .donate__custom-amount__input input {
        font-size:5.96181vw
    }
}

@media only screen and (max-width: 1370px) and (min-width:1051px) {
    .donate__custom-amount__input input {
        font-size:5.9562vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .donate__custom-amount__input input {
        font-style:7.20476vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate__custom-amount__input input {
        font-style:10.72384vw
    }
}

@media only screen and (max-width: 640px) {
    .donate__custom-amount__input input {
        font-style:17.22667vw
    }
}

.donate__custom-amount__input input::-webkit-input-placeholder {
    -webkit-appearance: none;
    appearance: none;
    color: #f3f0eb
}

.donate__custom-amount__input input:-moz-placeholder,.donate__custom-amount__input input::-moz-placeholder {
    -moz-appearance: none;
    appearance: none;
    color: #f3f0eb
}

.donate__custom-amount__input input:-ms-input-placeholder {
    appearance: none;
    color: #f3f0eb
}

.donate__custom-amount__input input[type=number]::-webkit-inner-spin-button,.donate__custom-amount__input input[type=number]::-webkit-outer-spin-button {
    -webkit-appearance: none;
    margin: 0
}

.donate__custom-currency {
    position: absolute;
    top: 0;
    left: 50%;
    margin-left: 20px
}

@media only screen and (min-width: 1921px) {
    .donate__custom-currency {
        margin-left:1.11111vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .donate__custom-currency {
        margin-left:1.11111vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .donate__custom-currency {
        margin-left:1.90476vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate__custom-currency {
        margin-left:2.32558vw
    }
}

@media only screen and (max-width: 640px) {
    .donate__custom-currency {
        margin-left:5.33333vw
    }
}

.donate__custom-currency .custom-select {
    z-index: 10
}

.donate__custom-currency .custom-select:before {
    content: "";
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100%;
    height: 50%;
    background-color: #fff;
    opacity: 0;
    transition: opacity .3s
}

.donate__custom-currency .custom-select.is-opened:before {
    opacity: 1
}

@media only screen and (max-width: 860px) {
    .donate__custom-currency .custom-select select {
        pointer-events:auto;
        position: absolute;
        top: 0;
        left: 0;
        z-index: 10;
        width: 100%;
        height: 100%
    }
}

.donate__custom-currency .custom-select__head {
    z-index: 2;
    border-color: transparent;
    border-radius: 30px;
    box-shadow: 0 5px 10px rgba(100,117,62,.08);
    font-size: 16px;
    padding-top: 10px;
    padding-bottom: 10px;
    text-transform: inherit
}

@media only screen and (min-width: 1921px) {
    .donate__custom-currency .custom-select__head {
        border-radius:1.66667vw;
        box-shadow: 0 .27778vw .55556vw rgba(100,117,62,.08);
        font-size: .88889vw;
        padding-top: .55556vw;
        padding-bottom: .55556vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .donate__custom-currency .custom-select__head {
        border-radius:1.66667vw;
        box-shadow: 0 .27778vw .55556vw rgba(100,117,62,.08);
        font-size: .88889vw;
        padding-top: .55556vw;
        padding-bottom: .55556vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .donate__custom-currency .custom-select__head {
        border-radius:2.85714vw;
        box-shadow: 0 .47619vw .95238vw rgba(100,117,62,.08);
        font-size: 1.33333vw;
        padding-top: .66667vw;
        padding-bottom: .66667vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate__custom-currency .custom-select__head {
        border-radius:3.48837vw;
        box-shadow: 0 .5814vw 1.16279vw rgba(100,117,62,.08);
        font-size: 1.62791vw;
        padding-top: .81395vw;
        padding-bottom: .81395vw
    }
}

@media only screen and (max-width: 640px) {
    .donate__custom-currency .custom-select__head {
        border-radius:8vw;
        box-shadow: 0 1.33333vw 2.66667vw rgba(100,117,62,.08);
        font-size: 3.73333vw;
        padding-top: 1.86667vw;
        padding-bottom: 1.86667vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .donate__custom-currency .custom-select__head .svg {
        right:.95238vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate__custom-currency .custom-select__head .svg {
        right:1.16279vw
    }
}

@media only screen and (max-width: 640px) {
    .donate__custom-currency .custom-select__head .svg {
        right:2.66667vw
    }
}

.donate__custom-currency .custom-select__content {
    z-index: 1;
    max-height: 350px;
    padding: 10px 0;
    border: none;
    border-radius: 0 0 15px 15px
}

@media only screen and (min-width: 1921px) {
    .donate__custom-currency .custom-select__content {
        max-height:19.44444vw;
        padding: .55556vw 0;
        border-radius: 0 0 .83333vw .83333vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .donate__custom-currency .custom-select__content {
        max-height:19.44444vw;
        padding: .55556vw 0;
        border-radius: 0 0 .83333vw .83333vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .donate__custom-currency .custom-select__content {
        max-height:33.33333vw;
        padding: .95238vw 0;
        border-radius: 0 0 1.42857vw 1.42857vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate__custom-currency .custom-select__content {
        max-height:40.69767vw;
        padding: 1.16279vw 0;
        border-radius: 0 0 1.74419vw 1.74419vw
    }
}

@media only screen and (max-width: 640px) {
    .donate__custom-currency .custom-select__content {
        max-height:93.33333vw;
        padding: 2.66667vw 0;
        border-radius: 0 0 4vw 4vw
    }
}

.donate__custom-currency .custom-select__item {
    font-size: 14px;
    line-height: 1;
    text-align: left;
    padding-left: 22px;
    padding-right: 0;
    text-transform: inherit
}

@media only screen and (min-width: 1921px) {
    .donate__custom-currency .custom-select__item {
        font-size:.77778vw;
        padding-left: 1.22222vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .donate__custom-currency .custom-select__item {
        font-size:.77778vw;
        padding-left: 1.22222vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .donate__custom-currency .custom-select__item {
        font-size:1.33333vw;
        padding-left: 2.09524vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate__custom-currency .custom-select__item {
        font-size:1.62791vw;
        padding-left: 2.55814vw
    }
}

@media only screen and (max-width: 640px) {
    .donate__custom-currency .custom-select__item {
        font-size:3.73333vw;
        padding-left: 5.86667vw
    }
}

.donate__impact {
    display: none;
    padding: 14px 20px;
    border-radius: 2px;
    background-color: #fff;
    color: #6b5a65
}

@media only screen and (min-width: 1921px) {
    .donate__impact {
        padding:.77778vw 1.11111vw;
        border-radius: .11111vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .donate__impact {
        padding:.77778vw 1.11111vw;
        border-radius: .11111vw
    }
}

@media only screen and (min-width: 1051px) {
    .donate__impact {
        display:block
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .donate__impact {
        padding:1.33333vw 1.90476vw;
        border-radius: .19048vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate__impact {
        padding:1.62791vw 2.32558vw;
        border-radius: .23256vw
    }
}

@media only screen and (max-width: 640px) {
    .donate__impact {
        padding:3.73333vw 5.33333vw;
        border-radius: .53333vw
    }
}

[data-toggle-wrap].is-open .donate__impact {
    display: block
}

@media only screen and (min-width: 1051px) {
    [data-toggle-wrap].is-open .donate__impact {
        display:none
    }
}

.donate__impact__wrapper:not(.is-showed) {
    display: none
}

.donate__impact__button {
    cursor: pointer;
    position: relative;
    display: flex;
    padding: 7px 72px 7px 20px;
    background-color: #fff
}

@media only screen and (min-width: 1921px) {
    .donate__impact__button {
        padding:.38889vw 4vw .38889vw 1.11111vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .donate__impact__button {
        padding:.38889vw 4vw .38889vw 1.11111vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .donate__impact__button {
        padding:.66667vw 6.85714vw .66667vw 1.90476vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate__impact__button {
        padding:.81395vw 8.37209vw .81395vw 2.32558vw
    }
}

@media only screen and (max-width: 640px) {
    .donate__impact__button {
        padding:1.86667vw 19.2vw 1.86667vw 5.33333vw
    }
}

.donate__impact__button__name {
    padding: 3px 0;
    font-weight: 500;
    color: #6b5a65;
    line-height: 1.714
}

@media only screen and (min-width: 1921px) {
    .donate__impact__button__name {
        padding:.16667vw 0
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .donate__impact__button__name {
        padding:.16667vw 0
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .donate__impact__button__name {
        padding:.28571vw 0
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate__impact__button__name {
        padding:.34884vw 0
    }
}

@media only screen and (max-width: 640px) {
    .donate__impact__button__name {
        padding:.8vw 0
    }
}

.donate__impact__button__icon {
    position: absolute;
    top: 50%;
    right: 10px;
    transform: translateY(-50%) rotate(-180deg);
    display: flex;
    align-items: center;
    justify-content: center;
    width: 32px;
    height: 32px;
    transition: transform .35s cubic-bezier(.455,.03,.515,.955)
}

@media only screen and (min-width: 1921px) {
    .donate__impact__button__icon {
        right:.55556vw;
        width: 1.77778vw;
        height: 1.77778vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .donate__impact__button__icon {
        right:.55556vw;
        width: 1.77778vw;
        height: 1.77778vw
    }
}

@media only screen and (min-width: 1051px) {
    .donate__impact__button__icon {
        transform:translateY(-50%)
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .donate__impact__button__icon {
        right:.95238vw;
        width: 3.04762vw;
        height: 3.04762vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate__impact__button__icon {
        right:1.16279vw;
        width: 3.72093vw;
        height: 3.72093vw
    }
}

@media only screen and (max-width: 640px) {
    .donate__impact__button__icon {
        right:2.66667vw;
        width: 8.53333vw;
        height: 8.53333vw
    }
}

[data-toggle-wrap].is-open .donate__impact__button__icon {
    transform: translateY(-50%)
}

@media only screen and (min-width: 1051px) {
    [data-toggle-wrap].is-open .donate__impact__button__icon {
        transform:translateY(-50%) rotate(-180deg)
    }
}

.donate__step:not(.is-active) {
    display: none
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate__step__inner {
        max-width:70%;
        margin-left: auto;
        margin-right: auto
    }
}

.donate__step__back {
    position: relative;
    display: block;
    margin-top: -1.11111vw;
    padding-left: 2.22222vw;
    margin-bottom: 3vw;
    font-weight: 500;
    font-size: .88889vw;
    line-height: 1.5;
    color: #362031
}

@media only screen and (min-width: 1921px) {
    .donate__step__back {
        padding-left:2.22222vw;
        margin-top: -1.11111vw;
        margin-bottom: 3vw;
        font-size: .88889vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .donate__step__back {
        padding-left:2.22222vw;
        margin-top: -1.11111vw;
        margin-bottom: 3vw;
        font-size: .88889vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .donate__step__back {
        padding-left:3.80952vw;
        margin-top: -1.90476vw;
        margin-bottom: 3.33333vw;
        font-size: 1.42857vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate__step__back {
        padding-left:4.65116vw;
        margin-top: -1.16279vw;
        margin-bottom: 4.06977vw;
        font-size: 1.74419vw
    }
}

@media only screen and (max-width: 640px) {
    .donate__step__back {
        padding-left:10.66667vw;
        margin-top: -2.66667vw;
        margin-bottom: 9.33333vw;
        font-size: 4vw
    }
}

.donate__step__back:hover svg {
    left: 0
}

.donate__step__back svg {
    position: absolute;
    top: 50%;
    left: .27778vw;
    transform: translateY(-50%) rotate(-90deg);
    transition: left .35s cubic-bezier(.4,0,0,1)
}

@media only screen and (min-width: 1921px) {
    .donate__step__back svg {
        left:.27778vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .donate__step__back svg {
        left:.27778vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .donate__step__back svg {
        left:.47619vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .donate__step__back svg {
        left:.5814vw
    }
}

@media only screen and (max-width: 640px) {
    .donate__step__back svg {
        left:1.33333vw
    }
}

.tab__switcher {
    margin: 40px auto
}

@media only screen and (min-width: 1921px) {
    .tab__switcher {
        margin:2.22222vw auto
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .tab__switcher {
        margin:2.22222vw auto
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .tab__switcher {
        margin:2.85714vw auto
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .tab__switcher {
        margin:3.48837vw auto
    }
}

@media only screen and (max-width: 640px) {
    .tab__switcher {
        margin:8vw auto
    }
}

.tab__item:not(.is-active) {
    display: none
}

.switcher {
    position: relative;
    display: block;
    width: 100%;
    height: 66px
}

@media only screen and (min-width: 1921px) {
    .switcher {
        height:3.66667vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .switcher {
        height:3.66667vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .switcher {
        height:5.33333vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .switcher {
        height:6.51163vw
    }
}

@media only screen and (max-width: 640px) {
    .switcher {
        height:14.93333vw
    }
}

.switcher__inner {
    display: flex;
    width: 100%;
    height: 100%;
    padding: 5px;
    background: #f3f0eb;
    border-radius: 60px
}

@media only screen and (min-width: 1921px) {
    .switcher__inner {
        padding:.27778vw;
        border-radius: 3.33333vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .switcher__inner {
        padding:.27778vw;
        border-radius: 3.33333vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .switcher__inner {
        padding:.38095vw;
        border-radius: 5.71429vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .switcher__inner {
        padding:.46512vw;
        border-radius: 6.97674vw
    }
}

@media only screen and (max-width: 640px) {
    .switcher__inner {
        padding:1.06667vw;
        border-radius: 16vw
    }
}

.switcher__slider {
    position: absolute;
    z-index: 0;
    display: block;
    width: 50%;
    height: 56px;
    border-radius: 60px;
    background: #fff;
    transition: margin .25s cubic-bezier(.4,0,0,1)
}

@media only screen and (min-width: 1921px) {
    .switcher__slider {
        height:3.11111vw;
        border-radius: 3.33333vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .switcher__slider {
        height:3.11111vw;
        border-radius: 3.33333vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .switcher__slider {
        height:4.57143vw;
        border-radius: 5.71429vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .switcher__slider {
        height:5.5814vw;
        border-radius: 6.97674vw
    }
}

@media only screen and (max-width: 640px) {
    .switcher__slider {
        height:12.8vw;
        border-radius: 16vw
    }
}

.switcher__slider__wrap {
    position: absolute;
    top: 0;
    left: 0;
    margin: 5px;
    width: calc(100% - 10px);
    height: calc(100% - 10px)
}

@media only screen and (min-width: 1921px) {
    .switcher__slider__wrap {
        margin:.27778vw;
        width: calc(100% - .55556vw);
        height: calc(100% - .55556vw)
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .switcher__slider__wrap {
        margin:.27778vw;
        width: calc(100% - .55556vw);
        height: calc(100% - .55556vw)
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .switcher__slider__wrap {
        margin:.38095vw;
        width: calc(100% - .7619vw);
        height: calc(100% - .7619vw)
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .switcher__slider__wrap {
        margin:.46512vw;
        width: calc(100% - .93023vw);
        height: calc(100% - .93023vw)
    }
}

@media only screen and (max-width: 640px) {
    .switcher__slider__wrap {
        margin:1.06667vw;
        width: calc(100% - 2.13333vw);
        height: calc(100% - 2.13333vw)
    }
}

.switcher__btn {
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    position: relative;
    z-index: 1;
    cursor: pointer;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 50%;
    height: 100%;
    font-size: 18px;
    line-height: 2;
    color: #9b8f97;
    text-align: center
}

@media only screen and (min-width: 1921px) {
    .switcher__btn {
        font-size:1vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .switcher__btn {
        font-size:1vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .switcher__btn {
        font-size:1.33333vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .switcher__btn {
        font-size:1.62791vw
    }
}

@media only screen and (max-width: 640px) {
    .switcher__btn {
        font-size:3.73333vw
    }
}

.switcher__btn.is-active {
    font-weight: 500;
    color: #362031;
    transition: all .35s cubic-bezier(.4,0,0,1) .1s
}

.share {
    display: flex;
    flex-direction: column;
    align-items: center;
    margin-top: 40px
}

@media only screen and (min-width: 1921px) {
    .share {
        margin-top:2.22222vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .share {
        margin-top:2.22222vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .share {
        margin-top:2.85714vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .share {
        margin-top:3.48837vw
    }
}

@media only screen and (max-width: 640px) {
    .share {
        margin-top:6.66667vw
    }
}

.share__title {
    margin-bottom: 30px
}

@media only screen and (min-width: 1921px) {
    .share__title {
        margin-bottom:1.66667vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .share__title {
        margin-bottom:1.66667vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .share__title {
        margin-bottom:2.85714vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .share__title {
        margin-bottom:2.90698vw
    }
}

@media only screen and (max-width: 640px) {
    .share__title {
        margin-bottom:6.66667vw
    }
}

.share__links {
    display: flex;
    margin: auto
}

.share__link {
    display: block;
    margin: 0 20px
}

@media only screen and (min-width: 1921px) {
    .share__link {
        margin:0 1.11111vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .share__link {
        margin:0 1.11111vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .share__link {
        margin:0 1.90476vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .share__link {
        margin:0 2.32558vw
    }
}

@media only screen and (max-width: 640px) {
    .share__link {
        margin:0 5.33333vw
    }
}

.share__link:hover svg {
    fill: #362031
}

.share__link svg {
    transition: fill .35s cubic-bezier(.4,0,0,1)
}

.main-screen {
    position: relative;
    width: 100%;
    height: 750px
}

@media only screen and (min-width: 1921px) {
    .main-screen {
        height:41.66667vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .main-screen {
        height:41.66667vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .main-screen {
        height:57.14286vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .main-screen {
        height:52.32558vw
    }
}

@media only screen and (max-width: 640px) {
    .main-screen {
        height:93.33333vw
    }
}

.main-screen .container,.main-screen__inner {
    position: relative;
    width: 100%;
    height: 100%
}

.main-screen__inner {
    z-index: 1
}

.main-screen__bg {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    display: block;
    margin: auto;
    z-index: 0
}

.main-screen__bg:after {
    content: "";
    z-index: 2;
    background: linear-gradient(0deg,rgba(0,0,0,.2),rgba(0,0,0,.2))
}

.main-screen__bg:after,.main-screen__bg__image {
    position: absolute;
    top: 0;
    left: 0;
    display: block;
    width: 100%;
    height: 100%
}

.main-screen__bg__image {
    z-index: 0;
    overflow: hidden
}

.main-screen__bg__image img,.main-screen__bg__image picture {
    position: absolute;
    top: 0;
    left: 0;
    display: block;
    width: 100%;
    height: 100%;
    z-index: 0;
    -o-object-fit: cover;
    object-fit: cover
}

.main-screen__copy {
    position: absolute;
    bottom: 36px;
    left: 0;
    color: #fff
}

@media only screen and (min-width: 1921px) {
    .main-screen__copy {
        bottom:2vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .main-screen__copy {
        bottom:2vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .main-screen__copy {
        bottom:2.38095vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .main-screen__copy {
        display:none
    }
}

@media only screen and (max-width: 640px) {
    .main-screen__copy {
        display:none
    }
}

.contribute {
    padding-top: 560px;
    padding-bottom: 250px;
    float: left
}

@media only screen and (min-width: 1921px) {
    .contribute {
        padding-top:31.11111vw;
        padding-bottom: 13.88889vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .contribute {
        padding-top:31.11111vw;
        padding-bottom: 13.88889vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .contribute {
        padding-top:40.7619vw;
        padding-bottom: 9.52381vw
    }
}

@media only screen and (max-width: 860px) {
    .contribute {
        float:none;
        order: 2
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .contribute {
        padding-top:9.30233vw;
        padding-bottom: 11.62791vw
    }
}

@media only screen and (max-width: 640px) {
    .contribute {
        padding-top:16vw;
        padding-bottom: 26.66667vw
    }
}

.contribute__sticky-wrapper {
    position: relative;
    max-width: 1680px;
    margin-top: -450px;
    margin-right: auto;
    margin-left: auto
}

@media only screen and (min-width: 1921px) {
    .contribute__sticky-wrapper {
        max-width:90%;
        margin-top: -25vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .contribute__sticky-wrapper {
        max-width:90%;
        margin-top: -25vw
    }
}

@media only screen and (max-width: 1050px) {
    .contribute__sticky-wrapper {
        max-width:100%
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .contribute__sticky-wrapper {
        margin-top:-34.09524vw
    }
}

@media only screen and (max-width: 860px) {
    .contribute__sticky-wrapper {
        display:flex;
        flex-direction: column;
        margin-top: 0
    }
}

.contribute__sticky-wrapper:after {
    content: "";
    clear: both;
    display: table
}

@media only screen and (max-width: 860px) {
    .contribute__sticky-wrapper:after {
        display:none
    }
}

.contribute__info {
    width: 650px
}

@media only screen and (min-width: 1921px) {
    .contribute__info {
        width:36.11111vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .contribute__info {
        width:36.11111vw
    }
}

@media only screen and (min-width: 1051px) {
    .contribute__info {
        margin-left:2.77778vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .contribute__info {
        width:42.85714vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .contribute__info {
        width:100%
    }
}

@media only screen and (max-width: 640px) {
    .contribute__info {
        width:100%
    }
}

.contribute__title {
    margin-bottom: 50px;
    color: #362031
}

@media only screen and (min-width: 1921px) {
    .contribute__title {
        margin-bottom:2.77778vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .contribute__title {
        margin-bottom:2.77778vw
    }
}

@media only screen and (min-width: 1051px) {
    .contribute__title {
        padding-right:1.94444vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .contribute__title {
        margin-bottom:2.85714vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .contribute__title {
        margin-bottom:3.48837vw
    }
}

@media only screen and (max-width: 640px) {
    .contribute__title {
        margin-bottom:8vw
    }
}

.contribute__list {
    margin-bottom: 60px;
    padding-left: 0;
    list-style: none
}

@media only screen and (min-width: 1921px) {
    .contribute__list {
        margin-bottom:3.33333vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .contribute__list {
        margin-bottom:3.33333vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .contribute__list {
        margin-bottom:5.71429vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .contribute__list {
        margin-bottom:6.97674vw
    }
}

@media only screen and (max-width: 640px) {
    .contribute__list {
        margin-bottom:16vw
    }
}

.contribute__list__top {
    margin-bottom: 30px;
    font-size: 20px;
    line-height: 1.8
}

@media only screen and (min-width: 1921px) {
    .contribute__list__top {
        margin-bottom:1.66667vw;
        font-size: 1.11111vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .contribute__list__top {
        margin-bottom:1.66667vw;
        font-size: 1.11111vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .contribute__list__top {
        margin-bottom:2.38095vw;
        font-size: 1.71429vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .contribute__list__top {
        margin-bottom:2.90698vw;
        font-size: 2.09302vw
    }
}

@media only screen and (max-width: 640px) {
    .contribute__list__top {
        margin-bottom:6.66667vw;
        font-size: 4.8vw
    }
}

.contribute__list__top p {
    margin: 0 0 15px
}

@media only screen and (min-width: 1921px) {
    .contribute__list__top p {
        margin:0 0 .83333vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .contribute__list__top p {
        margin:0 0 .83333vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .contribute__list__top p {
        margin:0 0 1.42857vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .contribute__list__top p {
        margin:0 0 1.74419vw
    }
}

@media only screen and (max-width: 640px) {
    .contribute__list__top p {
        margin:0 0 4vw
    }
}

.contribute__list li {
    position: relative;
    padding-left: 40px;
    font-size: 18px;
    line-height: 2
}

@media only screen and (min-width: 1921px) {
    .contribute__list li {
        padding-left:2.22222vw;
        font-size: 1vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .contribute__list li {
        padding-left:2.22222vw;
        font-size: 1vw
    }
}

@media only screen and (max-width: 1050px) {
    .contribute__list li {
        line-height:1.75
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .contribute__list li {
        padding-left:3.80952vw;
        font-size: 1.52381vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .contribute__list li {
        padding-left:4.65116vw;
        font-size: 1.86047vw
    }
}

@media only screen and (max-width: 640px) {
    .contribute__list li {
        padding-left:10.66667vw;
        font-size: 4.26667vw
    }
}

.contribute__list li[data-visibility] {
    transition: opacity .3s linear;
    will-change: opacity
}

.contribute__list li[data-visibility]:first-child {
    transition-delay: 0s
}

.contribute__list li[data-visibility]:nth-child(2) {
    transition-delay: .02s
}

.contribute__list li[data-visibility]:nth-child(3) {
    transition-delay: .04s
}

.contribute__list li[data-visibility]:nth-child(4) {
    transition-delay: .06s
}

.contribute__list li[data-visibility]:nth-child(5) {
    transition-delay: .08s
}

.contribute__list li[data-visibility]:nth-child(6) {
    transition-delay: .1s
}

.contribute__list li[data-visibility]:nth-child(7) {
    transition-delay: .12s
}

.contribute__list li[data-visibility]:nth-child(8) {
    transition-delay: .14s
}

.contribute__list li[data-visibility]:nth-child(9) {
    transition-delay: .16s
}

.contribute__list li[data-visibility]:nth-child(10) {
    transition-delay: .18s
}

.contribute__list li[data-visibility]:nth-child(11) {
    transition-delay: .2s
}

.contribute__list li[data-visibility]:nth-child(12) {
    transition-delay: .22s
}

.contribute__list li[data-visibility]:nth-child(13) {
    transition-delay: .24s
}

.contribute__list li[data-visibility]:nth-child(14) {
    transition-delay: .26s
}

.contribute__list li[data-visibility]:nth-child(15) {
    transition-delay: .28s
}

.contribute__list li[data-visibility]:nth-child(16) {
    transition-delay: .3s
}

.contribute__list li[data-visibility]:nth-child(17) {
    transition-delay: .32s
}

.contribute__list li[data-visibility]:nth-child(18) {
    transition-delay: .34s
}

.contribute__list li[data-visibility]:nth-child(19) {
    transition-delay: .36s
}

.contribute__list li[data-visibility]:nth-child(20) {
    transition-delay: .38s
}

.contribute__list li[data-visibility]:nth-child(21) {
    transition-delay: .4s
}

.contribute__list li[data-visibility]:not(.is-visible) {
    opacity: 0
}

.contribute__list li {
    margin-bottom: 20px
}

@media only screen and (min-width: 1921px) {
    .contribute__list li {
        margin-bottom:1.11111vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .contribute__list li {
        margin-bottom:1.11111vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .contribute__list li {
        margin-bottom:1.42857vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .contribute__list li {
        margin-bottom:1.74419vw
    }
}

@media only screen and (max-width: 640px) {
    .contribute__list li {
        margin-bottom:4vw
    }
}

.contribute__list li:before {
    content: "";
    position: absolute;
    top: 15px;
    left: 0;
    display: block;
    width: 20px;
    height: 20px;
    background-repeat: no-repeat;
    background-position: 50%;
    background-size: contain
}

@media only screen and (min-width: 1921px) {
    .contribute__list li:before {
        top:.55556vw;
        width: 1.11111vw;
        height: 1.11111vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .contribute__list li:before {
        top:.55556vw;
        width: 1.11111vw;
        height: 1.11111vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .contribute__list li:before {
        top:.47619vw;
        width: 1.90476vw;
        height: 1.90476vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .contribute__list li:before {
        top:.5814vw;
        width: 2.32558vw;
        height: 2.32558vw
    }
}

@media only screen and (max-width: 640px) {
    .contribute__list li:before {
        top:1.33333vw;
        width: 5.33333vw;
        height: 5.33333vw
    }
}

.contribute__description {
    padding: 40px 40px 40px 50px;
    border: 2px solid #362031;
    border-radius: 30px;
    font-weight: 500;
    font-size: 18px;
    line-height: 2
}

@media only screen and (min-width: 1921px) {
    .contribute__description {
        padding:2.22222vw 2.22222vw 2.22222vw 2.77778vw;
        border-width: .11111vw;
        border-radius: 1.66667vw;
        font-size: 1vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .contribute__description {
        padding:2.22222vw 2.22222vw 2.22222vw 2.77778vw;
        border-width: .11111vw;
        border-radius: 1.66667vw;
        font-size: 1vw
    }
}

@media only screen and (max-width: 1050px) {
    .contribute__description {
        line-height:1.75
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .contribute__description {
        padding:3.33333vw;
        border-radius: 1.90476vw;
        font-size: 1.52381vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .contribute__description {
        padding:4.06977vw;
        border-radius: 2.32558vw;
        font-size: 1.86047vw
    }
}

@media only screen and (max-width: 640px) {
    .contribute__description {
        padding:9.33333vw;
        border-radius: 5.33333vw;
        font-size: 4.26667vw
    }
}

.impact {
    position: relative;
    padding: 120px 0;
    background-color: #f3f0eb
}

@media only screen and (min-width: 1921px) {
    .impact {
        padding: 6.66667vw 0
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .impact {
        padding: 6.66667vw 0
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .impact {
        padding: 5.71429vw 0 9.52381vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .impact {
        padding: 6.97674vw 0 11.62791vw
    }
}

@media only screen and (max-width: 640px) {
    .impact {
        padding: 16vw 0 13.33333vw
    }
}

.impact__bg {
    position: absolute;
    top: 70px;
    left: 50%;
    transform: translateX(-50%);
    z-index: 1;
    display: block;
    width: 442px
}

@media only screen and (min-width: 1921px) {
    .impact__bg {
        top:3.88889vw;
        width: 24.55556vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .impact__bg {
        top:3.88889vw;
        width: 24.55556vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .impact__bg {
        top:9.52381vw;
        width: 28.57143vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .impact__bg {
        top:11.62791vw;
        width: 34.88372vw
    }
}

@media only screen and (max-width: 640px) {
    .impact__bg {
        top:26.66667vw;
        right: 5.33333vw;
        left: 5.33333vw;
        transform: none;
        width: auto
    }
}

.impact__bg svg {
    display: block;
    max-width: 100%;
    width: 100%
}

.impact__bg .finger {
    position: relative
}

.impact__bg .finger:first-child {
    -webkit-animation: finger 2s linear infinite forwards;
    animation: finger 2s linear infinite forwards;
    -webkit-animation-delay: 0s;
    animation-delay: 0s
}

.impact__bg .finger:nth-child(2) {
    -webkit-animation: finger 2s linear infinite forwards;
    animation: finger 2s linear infinite forwards;
    -webkit-animation-delay: .15s;
    animation-delay: .15s
}

.impact__bg .finger:nth-child(3) {
    -webkit-animation: finger 2s linear infinite forwards;
    animation: finger 2s linear infinite forwards;
    -webkit-animation-delay: .3s;
    animation-delay: .3s
}

.impact__bg .finger:nth-child(4) {
    -webkit-animation: finger 2s linear infinite forwards;
    animation: finger 2s linear infinite forwards;
    -webkit-animation-delay: .45s;
    animation-delay: .45s
}

.impact__bg .finger:nth-child(5) {
    -webkit-animation: finger 2s linear infinite forwards;
    animation: finger 2s linear infinite forwards;
    -webkit-animation-delay: .6s;
    animation-delay: .6s
}

.impact__bg .finger:nth-child(6) {
    -webkit-animation: finger 2s linear infinite forwards;
    animation: finger 2s linear infinite forwards;
    -webkit-animation-delay: .75s;
    animation-delay: .75s
}

.impact__bg .finger:nth-child(7) {
    -webkit-animation: finger 2s linear infinite forwards;
    animation: finger 2s linear infinite forwards;
    -webkit-animation-delay: .9s;
    animation-delay: .9s
}

.impact__bg .finger:nth-child(8) {
    -webkit-animation: finger 2s linear infinite forwards;
    animation: finger 2s linear infinite forwards;
    -webkit-animation-delay: 1.05s;
    animation-delay: 1.05s
}

.impact__bg .finger:nth-child(9) {
    -webkit-animation: finger 2s linear infinite forwards;
    animation: finger 2s linear infinite forwards;
    -webkit-animation-delay: 1.2s;
    animation-delay: 1.2s
}

.impact__bg .finger:nth-child(10) {
    -webkit-animation: finger 2s linear infinite forwards;
    animation: finger 2s linear infinite forwards;
    -webkit-animation-delay: 1.35s;
    animation-delay: 1.35s
}

.impact__bg .finger:nth-child(11) {
    -webkit-animation: finger 2s linear infinite forwards;
    animation: finger 2s linear infinite forwards;
    -webkit-animation-delay: 1.5s;
    animation-delay: 1.5s
}

@-webkit-keyframes finger {
    0% {
        opacity: 0
    }

    10% {
        opacity: 1
    }

    50% {
        opacity: 0
    }

    to {
        opacity: 0
    }
}

@keyframes finger {
    0% {
        opacity: 0
    }

    10% {
        opacity: 1
    }

    50% {
        opacity: 0
    }

    to {
        opacity: 0
    }
}

.impact__inner {
    position: relative;
    z-index: 2
}

.impact__info {
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    margin-bottom: 100px
}

@media only screen and (min-width: 1921px) {
    .impact__info {
        margin-bottom:5.55556vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .impact__info {
        margin-bottom:5.55556vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .impact__info {
        margin-bottom:3.80952vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .impact__info {
        margin-bottom:4.65116vw
    }
}

@media only screen and (max-width: 640px) {
    .impact__info {
        margin-bottom:10.66667vw
    }
}

.impact__title {
    max-width: 1000px;
    margin-bottom: 50px;
    font-weight: 700;
    color: #362031
}

@media only screen and (min-width: 1921px) {
    .impact__title {
        max-width:55.55556vw;
        margin-bottom: 2.77778vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .impact__title {
        max-width:55.55556vw;
        margin-bottom: 2.77778vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .impact__title {
        max-width:59.52381vw;
        margin-bottom: 2.85714vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .impact__title {
        max-width:72.67442vw;
        margin-bottom: 3.48837vw
    }
}

@media only screen and (max-width: 640px) {
    .impact__title {
        max-width:100%;
        margin-bottom: 8vw;
        padding: 0 2.66667vw
    }
}

.impact__subtitle {
    max-width: 800px;
    font-weight: 500;
    font-size: 20px;
    line-height: 1.8;
    color: #362031
}

@media only screen and (min-width: 1921px) {
    .impact__subtitle {
        max-width:44.44444vw;
        font-size: 1.11111vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .impact__subtitle {
        max-width:44.44444vw;
        font-size: 1.11111vw
    }
}

@media only screen and (max-width: 1050px) {
    .impact__subtitle {
        line-height:1.66
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .impact__subtitle {
        max-width:69.52381vw;
        font-size: 1.71429vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .impact__subtitle {
        max-width:82.55814vw;
        font-size: 2.09302vw
    }
}

@media only screen and (max-width: 640px) {
    .impact__subtitle {
        max-width:100%;
        font-size: 4.8vw
    }
}

.impact__items {
    display: flex;
    justify-content: flex-start;
    flex-wrap: wrap;
    justify-content: center;
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .impact__items {
        margin:-.95238vw;
        padding: 0 4.7619vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .impact__items {
        margin:-.81395vw
    }
}

@media only screen and (max-width: 640px) {
    .impact__items {
        margin:-1.86667vw 0
    }
}

.impact__item {
    width: calc(25% - 30px);
    margin: 0 15px;
    padding: 40px 30px;
    border-radius: 30px;
    background: #fff;
    text-align: center
}

@media only screen and (min-width: 1921px) {
    .impact__item {
        width:calc(25% - 1.66667vw);
        margin: 0 .83333vw;
        padding: 2.22222vw 1.66667vw;
        border-radius: 1.66667vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .impact__item {
        width:calc(25% - 1.66667vw);
        margin: 0 .83333vw;
        padding: 2.22222vw 1.66667vw;
        border-radius: 1.66667vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .impact__item {
        width:calc(50% - 1.90476vw);
        margin: .95238vw;
        padding: 4.28571vw 4.7619vw;
        border-radius: 1.90476vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .impact__item {
        width:calc(50% - 1.62791vw);
        margin: .81395vw;
        padding: 4.06977vw 5.81395vw;
        border-radius: 2.32558vw
    }
}

@media only screen and (max-width: 640px) {
    .impact__item {
        width:100%;
        margin: 1.86667vw 0;
        padding: 8vw;
        border-radius: 5.33333vw
    }
}

.impact__item[data-visibility] {
    transition: opacity .35s ease-in-out;
    will-change: opacity
}

.impact__item[data-visibility]:nth-child(4n-4) {
    transition-delay: 50ms
}

.impact__item[data-visibility]:nth-child(4n-3) {
    transition-delay: 10ms
}

.impact__item[data-visibility]:nth-child(4n-2) {
    transition-delay: .15s
}

.impact__item[data-visibility]:nth-child(4n-1) {
    transition-delay: .2s
}

.impact__item[data-visibility]:not(.is-visible) {
    opacity: 0
}

.impact__donation-size {
    font-weight: 700;
    font-size: 64px;
    line-height: 1.125
}

.impact__donation-size_mid {
    font-weight: 700;
    font-size: 32px;
    line-height: 1.125
}

@media only screen and (min-width: 1921px) {
    .impact__donation-size {
        font-size:3.55556vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .impact__donation-size {
        font-size:3.55556vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .impact__donation-size {
        font-size:4.57143vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .impact__donation-size {
        font-size:5.5814vw
    }
}

@media only screen and (max-width: 640px) {
    .impact__donation-size {
        font-weight:800;
        font-size: 12.8vw
    }
}

.impact__donation-wave {
    width: 52px;
    height: 5px;
    margin: 15px 0 5px;
    fill: #362031
}

@media only screen and (min-width: 1921px) {
    .impact__donation-wave {
        width:2.88889vw;
        height: .27778vw;
        margin: .83333vw 0 .27778vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .impact__donation-wave {
        width:2.88889vw;
        height: .27778vw;
        margin: .83333vw 0 .27778vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .impact__donation-wave {
        width:4.95238vw;
        height: .47619vw;
        margin: 1.16279vw 0
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .impact__donation-wave {
        width:6.04651vw;
        height: .5814vw;
        margin: 1.16279vw 0
    }
}

@media only screen and (max-width: 640px) {
    .impact__donation-wave {
        width:13.86667vw;
        height: 1.33333vw;
        margin: 2.66667vw 0
    }
}

.impact__donation-desc {
    font-family: 'Fira Sans',Inter,sans-serif;
    font-size: 16px;
    line-height: 1.875;
    color: #9b8f97;
    padding: 0 15px
}

@media only screen and (min-width: 1921px) {
    .impact__donation-desc {
        font-size:.88889vw;
        padding: 0 .83333vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .impact__donation-desc {
        font-size:.88889vw;
        padding: 0 .83333vw
    }
}

@media only screen and (max-width: 1050px) {
    .impact__donation-desc {
        line-height:1.75
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .impact__donation-desc {
        font-size:1.42857vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .impact__donation-desc {
        font-size:1.74419vw
    }
}

@media only screen and (max-width: 640px) {
    .impact__donation-desc {
        font-size:4.26667vw
    }
}

.media--gallery-single .media__gallery {
    max-width: 1020px;
    width: 100%;
    margin-right: auto;
    margin-left: auto;
    transform: translateY(146px)
}

@media only screen and (min-width: 1921px) {
    .media--gallery-single .media__gallery {
        transform:translateY(8.11111vw);
        max-width: 56.66667vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .media--gallery-single .media__gallery {
        transform:translateY(8.11111vw);
        max-width: 56.66667vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .media--gallery-single .media__gallery {
        transform:translateY(9.52381vw);
        max-width: 76.19048vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .media--gallery-single .media__gallery {
        transform:translateY(11.62791vw);
        max-width: 69.76744vw
    }
}

@media only screen and (max-width: 640px) {
    .media--gallery-single .media__gallery {
        transform:translateY(32vw);
        max-width: 100%
    }
}

.media--gallery-single .media__gallery__item {
    max-width: 100%;
    width: 100%;
    height: 570px;
    margin: 0 auto;
    border-radius: 30px
}

@media only screen and (min-width: 1921px) {
    .media--gallery-single .media__gallery__item {
        height:30.55556vw;
        border-radius: 1.66667vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .media--gallery-single .media__gallery__item {
        height:30.55556vw;
        border-radius: 1.66667vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .media--gallery-single .media__gallery__item {
        height:40vw;
        border-radius: 2.85714vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .media--gallery-single .media__gallery__item {
        height:46.51163vw;
        border-radius: 3.48837vw
    }
}

@media only screen and (max-width: 640px) {
    .media--gallery-single .media__gallery__item {
        height:auto;
        border-radius: 8vw
    }
}

.media--only-video {
    padding-bottom: 200px
}

@media only screen and (min-width: 1921px) {
    .media--only-video {
        padding-bottom:11.11111vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .media--only-video {
        padding-bottom:11.11111vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .media--only-video {
        padding-bottom:14.28571vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .media--only-video {
        padding-bottom:17.44186vw
    }
}

@media only screen and (max-width: 640px) {
    .media--only-video {
        padding-bottom:26.66667vw
    }
}

.media--only-video .media__description {
    margin-bottom: 90px
}

@media only screen and (min-width: 1921px) {
    .media--only-video .media__description {
        margin-bottom:5vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .media--only-video .media__description {
        margin-bottom:5vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .media--only-video .media__description {
        margin-bottom:5.71429vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .media--only-video .media__description {
        margin-bottom:6.97674vw
    }
}

@media only screen and (max-width: 640px) {
    .media--only-video .media__description {
        margin-bottom:13.33333vw
    }
}

.media--only-gallery {
    padding-bottom: 200px
}

@media only screen and (min-width: 1921px) {
    .media--only-gallery {
        padding-bottom:11.11111vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .media--only-gallery {
        padding-bottom:11.11111vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .media--only-gallery {
        padding-bottom:14.28571vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .media--only-gallery {
        padding-bottom:17.44186vw
    }
}

@media only screen and (max-width: 640px) {
    .media--only-gallery {
        padding-bottom:26.66667vw
    }
}

.media--only-gallery .media__gallery {
    transform: translateY(-120px);
    flex-wrap: nowrap;
    align-items: center;
    margin: 0 -10px -60px
}

@media only screen and (min-width: 1921px) {
    .media--only-gallery .media__gallery {
        transform:translateY(-6.66667vw);
        margin: 0 -.55556vw -3.33333vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .media--only-gallery .media__gallery {
        transform:translateY(-6.66667vw);
        margin: 0 -.55556vw -3.33333vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .media--only-gallery .media__gallery {
        transform:translateY(-9.52381vw);
        margin: 0 -.95238vw -4.7619vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .media--only-gallery .media__gallery {
        transform:translateY(-11.62791vw);
        margin: 0 -1.16279vw -5.81395vw
    }
}

@media only screen and (max-width: 640px) {
    .media--only-gallery .media__gallery {
        flex-wrap:wrap;
        transform: translateY(-26.66667vw);
        margin: -1.86667vw 0 -18.66667vw
    }
}

.media--only-gallery .media__gallery__item {
    flex: 1 1 auto;
    height: 350px;
    margin: 0 10px
}

@media only screen and (min-width: 1921px) {
    .media--only-gallery .media__gallery__item {
        height:19.44444vw;
        margin: 0 .55556vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .media--only-gallery .media__gallery__item {
        height:19.44444vw;
        margin: 0 .55556vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .media--only-gallery .media__gallery__item {
        height:21.90476vw;
        margin: 0 .95238vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .media--only-gallery .media__gallery__item {
        height:18.60465vw;
        margin: 0 1.16279vw
    }
}

@media only screen and (max-width: 640px) {
    .media--only-gallery .media__gallery__item {
        width:100%;
        height: auto;
        margin: 1.86667vw 0
    }
}

.media--only-gallery .media__gallery__item[data-visibility] {
    transition: opacity .3s linear;
    will-change: opacity
}

.media--only-gallery .media__gallery__item[data-visibility]:first-child {
    transition-delay: 0s
}

.media--only-gallery .media__gallery__item[data-visibility]:nth-child(2) {
    transition-delay: .02s
}

.media--only-gallery .media__gallery__item[data-visibility]:nth-child(3) {
    transition-delay: .04s
}

.media--only-gallery .media__gallery__item[data-visibility]:nth-child(4) {
    transition-delay: .06s
}

.media--only-gallery .media__gallery__item[data-visibility]:not(.is-visible) {
    opacity: 0
}

.media--only-gallery .media__gallery__item:nth-child(2) {
    flex-shrink: 0;
    width: 600px;
    height: 450px;
    transform: none
}

@media only screen and (min-width: 1921px) {
    .media--only-gallery .media__gallery__item:nth-child(2) {
        width:33.33333vw;
        height: 25vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .media--only-gallery .media__gallery__item:nth-child(2) {
        width:33.33333vw;
        height: 25vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .media--only-gallery .media__gallery__item:nth-child(2) {
        width:38.09524vw;
        height: 28.57143vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .media--only-gallery .media__gallery__item:nth-child(2) {
        width:34.88372vw;
        height: 26.16279vw
    }
}

@media only screen and (max-width: 640px) {
    .media--only-gallery .media__gallery__item:nth-child(2) {
        flex-shrink:inherit;
        width: auto;
        height: auto
    }
}

.media--only-gallery .media__description {
    margin-bottom: 90px
}

@media only screen and (min-width: 1921px) {
    .media--only-gallery .media__description {
        margin-bottom:5vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .media--only-gallery .media__description {
        margin-bottom:5vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .media--only-gallery .media__description {
        margin-bottom:5.71429vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .media--only-gallery .media__description {
        margin-bottom:6.97674vw
    }
}

@media only screen and (max-width: 640px) {
    .media--only-gallery .media__description {
        margin-bottom:13.33333vw
    }
}

.media__inner {
    display: flex;
    flex-direction: column;
    background: #362031;
    padding: 50px 0 50px 0;
}

.media__video {
    display: flex;
    justify-content: center;
    max-width: 100%;
    width: 100%;
    border-radius: 30px;
    overflow: hidden
}

@media only screen and (min-width: 1921px) {
    .media__video {
        border-radius: 1.66667vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .media__video {
        border-radius: 1.66667vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .media__video {
        border-radius: 2.85714vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .media__video {
        border-radius: 3.48837vw
    }
}

@media only screen and (max-width: 640px) {
    .media__video {
        border-radius: 8vw
    }
}

.media__video iframe {
    width: 100%;
    height: 570px
}

@media only screen and (min-width: 1921px) {
    .media__video iframe {
        height:31.66667vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .media__video iframe {
        height:31.66667vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .media__video iframe {
        height:40vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .media__video iframe {
        height:46.51163vw
    }
}

@media only screen and (max-width: 640px) {
    .media__video iframe {
        height:76vw
    }
}

.media__video__wrapper {
    display: flex;
    flex-direction: column;
    align-items: center;
    max-width: 1020px;
    width: 100%;
    margin: auto;
    border-radius: 30px;
}

@media only screen and (min-width: 1921px) {
    .media__video__wrapper {
        max-width: 56.66667vw;
        border-radius: 1.66667vw;
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .media__video__wrapper {
        max-width: 56.66667vw;
        border-radius: 1.66667vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .media__video__wrapper {
        max-width: 76.19048vw;
        border-radius: 1.90476vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .media__video__wrapper {
        max-width: 69.76744vw;
        border-radius: 2.32558vw
    }
}

@media only screen and (max-width: 640px) {
    .media__video__wrapper {
        max-width: 100%;
        border-radius: 5.33333vw
    }
}

.media__description__title {
    max-width: 710px;
    margin: 60px auto auto;
    font-weight: 700;
    font-size: 30px;
    line-height: 1.2;
    color: #fff;
    text-align: center
}

@media only screen and (min-width: 1921px) {
    .media__description__title {
        max-width:39.44444vw;
        margin: 3.33333vw auto auto;
        font-size: 1.66667vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .media__description__title {
        max-width:39.44444vw;
        margin: 3.33333vw auto auto;
        font-size: 1.66667vw
    }
}

@media only screen and (max-width: 1050px) {
    .media__description__title {
        line-height:1.5
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .media__description__title {
        max-width:47.61905vw;
        margin-top: 2.85714vw;
        font-size: 1.90476vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .media__description__title {
        max-width:58.13953vw;
        margin-top: 3.48837vw;
        font-size: 2.32558vw
    }
}

@media only screen and (max-width: 640px) {
    .media__description__title {
        max-width:100%;
        font-size: 5.33333vw;
        margin-top: 8vw;
        padding: 0 2.66667vw
    }
}

.media__wave {
    width: 100px;
    height: 8px;
    fill: #fff
}

@media only screen and (min-width: 1921px) {
    .media__wave {
        width:5.55556vw;
        height: .44444vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .media__wave {
        width:5.55556vw;
        height: .44444vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .media__wave {
        width:9.52381vw;
        height: .7619vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .media__wave {
        width:8.13953vw;
        height: .5814vw
    }
}

@media only screen and (max-width: 640px) {
    .media__wave {
        width:26.66667vw;
        height: 2.13333vw
    }
}

.media__gallery {
    display: flex;
    justify-content: center;
    flex-wrap: wrap;
    margin: 0 -17px;
}

@media only screen and (min-width: 1921px) {
    .media__gallery {
        margin: 0 -.94444vw;
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .media__gallery {
        margin: 0 -.94444vw;
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .media__gallery {
        margin: 0 -.95238vw;
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .media__gallery {
        margin: 0 -.81395vw;
    }
}

@media only screen and (max-width: 640px) {
    .media__gallery {
        margin: -1.86667vw 0;
    }
}

.media__gallery__item {
    position: relative;
    width: calc(33.33% - 34px);
    margin: 0 17px;
    border-radius: 20px;
    overflow: hidden
}

@media only screen and (min-width: 1921px) {
    .media__gallery__item {
        width:calc(33.33% - 1.88889vw);
        margin: 0 .94444vw;
        border-radius: 1.11111vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .media__gallery__item {
        width:calc(33.33% - 1.88889vw);
        margin: 0 .94444vw;
        border-radius: 1.11111vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .media__gallery__item {
        width:calc(33.33% - 1.90476vw);
        margin: 0 .95238vw;
        border-radius: 1.90476vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .media__gallery__item {
        width:calc(33.33% - 1.62791vw);
        margin: 0 .81395vw;
        border-radius: 2.32558vw
    }
}

@media only screen and (max-width: 640px) {
    .media__gallery__item {
        width:100%;
        margin: 1.86667vw 0;
        border-radius: 5.33333vw
    }
}

.media__gallery__item:nth-child(2) {
    transform: translateY(-40px)
}

@media only screen and (min-width: 1921px) {
    .media__gallery__item:nth-child(2) {
        transform:translateY(-2.22222vw)
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .media__gallery__item:nth-child(2) {
        transform:translateY(-2.22222vw)
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .media__gallery__item:nth-child(2) {
        transform:translateY(-3.33333vw)
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .media__gallery__item:nth-child(2) {
        transform:translateY(-4.06977vw)
    }
}

@media only screen and (max-width: 640px) {
    .media__gallery__item:nth-child(2) {
        transform:none
    }
}

.media__gallery__img {
    position: relative;
    width: 100%;
    height: 100%
}

.media__gallery__img:after {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    z-index: 1;
    width: 100%;
    height: 100%;
    background: linear-gradient(0deg,rgba(31,42,56,.2),rgba(31,42,56,.2))
}

.media__gallery__img img {
    display: block;
    max-width: 100%;
    width: 100%;
    height: 100%;
    -o-object-fit: cover;
    object-fit: cover
}

.media__gallery__desc {
    position: absolute;
    right: 30px;
    bottom: 30px;
    left: 30px;
    z-index: 2;
    font-weight: 700;
    font-size: 16px;
    line-height: 1.25;
    color: #fff
}

@media only screen and (min-width: 1921px) {
    .media__gallery__desc {
        right:1.66667vw;
        bottom: 1.66667vw;
        left: 1.66667vw;
        font-size: .88889vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .media__gallery__desc {
        right:1.66667vw;
        bottom: 1.66667vw;
        left: 1.66667vw;
        font-size: .88889vw
    }
}

@media only screen and (max-width: 1050px) {
    .media__gallery__desc {
        line-height:1.42
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .media__gallery__desc {
        font-size:1.33333vw;
        right: 1.90476vw;
        bottom: 1.90476vw;
        left: 1.90476vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .media__gallery__desc {
        font-size:1.62791vw;
        right: 2.32558vw;
        bottom: 2.32558vw;
        left: 2.32558vw
    }
}

@media only screen and (max-width: 640px) {
    .media__gallery__desc {
        font-size:3.73333vw;
        right: 6.66667vw;
        bottom: 6.66667vw;
        left: 6.66667vw
    }
}

.thanks {
    margin-bottom: 200px
}

@media only screen and (min-width: 1921px) {
    .thanks {
        margin-bottom:11.11111vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .thanks {
        margin-bottom:11.11111vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .thanks {
        margin-bottom:9.52381vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .thanks {
        margin-bottom:11.62791vw
    }
}

@media only screen and (max-width: 640px) {
    .thanks {
        margin-bottom:26.66667vw
    }
}

.thanks__inner {
    display: flex;
    flex-direction: column;
    align-items: center
}

.thanks__icon {
    width: 29px;
    height: auto;
    margin-bottom: 40px;
    fill: #362031
}

@media only screen and (min-width: 1921px) {
    .thanks__icon {
        width:1.61111vw;
        margin-bottom: 2.22222vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .thanks__icon {
        width:1.61111vw;
        margin-bottom: 2.22222vw
    }
}

@media only screen and (max-width: 1050px) and (min-width:861px) {
    .thanks__icon {
        width:2.7619vw;
        margin-bottom: 3.80952vw
    }
}

@media only screen and (max-width: 860px) and (min-width:641px) {
    .thanks__icon {
        width:3.37209vw;
        margin-bottom: 4.65116vw
    }
}

@media only screen and (max-width: 640px) {
    .thanks__icon {
        width:7.73333vw;
        margin-bottom: 10.66667vw
    }
}

.thanks__desc {
    max-width: 767px;
    margin: auto;
    color: #362031;
    text-align: center
}

@media only screen and (min-width: 1921px) {
    .thanks__desc {
        max-width:42.61111vw
    }
}

@media only screen and (max-width: 1679px) and (min-width:1051px) {
    .thanks__desc {
        max-width:42.61111vw
    }
}

@media only screen and (max-width: 1050px) {
    .thanks__desc {
        max-width:48.57143vw
    }
}

@media only screen and (max-width: 640px) {
    .thanks__desc {
        max-width:204.53333vw
    }
}


/* DKD brand overrides */
.btn--orange {
    color: #362031;
}

.brand-button,
.btn {
    text-transform: uppercase;
    font-weight: 800;
    letter-spacing: .03em;
}

.donate-button-expand {
    color: #362031;
}

h1, h2, h3, .donate-title {
    font-weight: 800;
}
