public with sharing class ComgatePaymentStatusResponseWrapper {
    public Integer code;
    public String message;
    public String test;
    public Decimal price;
    public String curr;
    public String label;
    public String refId;
    public String payerId;
    public String method;
    public String account;
    public String email;
    public String name;
    public String phone;
    public String transId;
    public String status;
    public String payerName;
    public String payerAcc;
    public String fee;
    public String vs;
    public String cardValid;
    public String cardNumber;
    public Decimal appliedFee;
    public String appliedFeeType;
    public String paymentErrorReason;
}